// Code generated by tools/surfacegen (wrappers) - DO NOT EDIT.
package formulation

import (
	"bytes"
	"context"
	"crypto/tls"
	"database/sql"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"regexp"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/lib/pq/oid"
	"github.com/stackql/any-sdk/anysdk"
	"github.com/stackql/any-sdk/pkg/auth_util"
	"github.com/stackql/any-sdk/pkg/client"
	"github.com/stackql/any-sdk/pkg/constants"
	"github.com/stackql/any-sdk/pkg/db/sqlcontrol"
	"github.com/stackql/any-sdk/pkg/dto"
	"github.com/stackql/any-sdk/pkg/graphql"
	"github.com/stackql/any-sdk/pkg/httpelement"
	"github.com/stackql/any-sdk/pkg/internaldto"
	"github.com/stackql/any-sdk/pkg/local_template_executor"
	"github.com/stackql/any-sdk/pkg/name_mangle"
	"github.com/stackql/any-sdk/pkg/netutils"
	"github.com/stackql/any-sdk/pkg/providerinvoker"
	"github.com/stackql/any-sdk/pkg/response"
	"github.com/stackql/any-sdk/pkg/stream_transform"
	"github.com/stackql/any-sdk/pkg/streaming"
	"github.com/stackql/any-sdk/pkg/surface"
	"github.com/stackql/any-sdk/public/discovery"
	"github.com/stackql/any-sdk/public/persistence"
	"github.com/stackql/any-sdk/public/radix_tree_address_space"
	"github.com/stackql/any-sdk/public/sqlengine"
	"github.com/stackql/stackql-parser/go/sqltypes"
	"github.com/stackql/stackql-parser/go/vt/sqlparser"
)

func wrapMapString_Addressable(in map[string]anysdk.Addressable) map[string]Addressable {
	if in == nil {
		return nil
	}
	out := make(map[string]Addressable, len(in))
	for k, v := range in {
		out[k] = &wrappedAddressable{inner: v}
	}
	return out
}

func unwrapMapString_Addressable(in map[string]*wrappedAddressable) map[string]anysdk.Addressable {
	if in == nil {
		return nil
	}
	out := make(map[string]anysdk.Addressable, len(in))
	for k, v := range in {
		out[k] = v.inner
	}
	return out
}

func wrapMapString_ProviderDescription(in map[string]anysdk.ProviderDescription) map[string]ProviderDescription {
	if in == nil {
		return nil
	}
	out := make(map[string]ProviderDescription, len(in))
	for k, v := range in {
		out[k] = &wrappedProviderDescription{inner: v}
	}
	return out
}

func unwrapMapString_ProviderDescription(in map[string]*wrappedProviderDescription) map[string]anysdk.ProviderDescription {
	if in == nil {
		return nil
	}
	out := make(map[string]anysdk.ProviderDescription, len(in))
	for k, v := range in {
		out[k] = v.inner
	}
	return out
}

func wrapMapString_ProviderService(in map[string]anysdk.ProviderService) map[string]ProviderService {
	if in == nil {
		return nil
	}
	out := make(map[string]ProviderService, len(in))
	for k, v := range in {
		out[k] = &wrappedProviderService{inner: v}
	}
	return out
}

func unwrapMapString_ProviderService(in map[string]*wrappedProviderService) map[string]anysdk.ProviderService {
	if in == nil {
		return nil
	}
	out := make(map[string]anysdk.ProviderService, len(in))
	for k, v := range in {
		out[k] = v.inner
	}
	return out
}

func wrapMapString_Resource(in map[string]anysdk.Resource) map[string]Resource {
	if in == nil {
		return nil
	}
	out := make(map[string]Resource, len(in))
	for k, v := range in {
		out[k] = &wrappedResource{inner: v}
	}
	return out
}

func unwrapMapString_Resource(in map[string]*wrappedResource) map[string]anysdk.Resource {
	if in == nil {
		return nil
	}
	out := make(map[string]anysdk.Resource, len(in))
	for k, v := range in {
		out[k] = v.inner
	}
	return out
}

func wrapPtr_AuthCtx(in *dto.AuthCtx) *AuthCtx {
	if in == nil {
		return nil
	}
	return &AuthCtx{inner: in}
}

func wrapSlice_Column(in []anysdk.Column) []Column {
	if in == nil {
		return nil
	}
	out := make([]Column, 0, len(in))
	for _, v := range in {
		out = append(out, &wrappedColumn{inner: v})
	}
	return out
}

func unwrapSlice_Column(in []*wrappedColumn) []anysdk.Column {
	if in == nil {
		return nil
	}
	out := make([]anysdk.Column, 0, len(in))
	for _, v := range in {
		out = append(out, v.inner)
	}
	return out
}

func wrapSlice_HTTPArmouryParameters(in []anysdk.HTTPArmouryParameters) []HTTPArmouryParameters {
	if in == nil {
		return nil
	}
	out := make([]HTTPArmouryParameters, 0, len(in))
	for _, v := range in {
		out = append(out, &wrappedHTTPArmouryParameters{inner: v})
	}
	return out
}

func unwrapSlice_HTTPArmouryParameters(in []HTTPArmouryParameters) []anysdk.HTTPArmouryParameters {
	if in == nil {
		return nil
	}
	out := make([]anysdk.HTTPArmouryParameters, 0, len(in))
	for _, v := range in {
		v := v.(*wrappedHTTPArmouryParameters)
		out = append(out, v.inner)
	}
	return out
}

func wrapSlice_SQLExternalColumn(in []anysdk.SQLExternalColumn) []SQLExternalColumn {
	if in == nil {
		return nil
	}
	out := make([]SQLExternalColumn, 0, len(in))
	for _, v := range in {
		out = append(out, &wrappedSQLExternalColumn{inner: v})
	}
	return out
}

func unwrapSlice_SQLExternalColumn(in []*wrappedSQLExternalColumn) []anysdk.SQLExternalColumn {
	if in == nil {
		return nil
	}
	out := make([]anysdk.SQLExternalColumn, 0, len(in))
	for _, v := range in {
		out = append(out, v.inner)
	}
	return out
}

func wrapSlice_StandardOperationStore(in []anysdk.StandardOperationStore) []StandardOperationStore {
	if in == nil {
		return nil
	}
	out := make([]StandardOperationStore, 0, len(in))
	for _, v := range in {
		out = append(out, &wrappedStandardOperationStore{inner: v})
	}
	return out
}

func unwrapSlice_StandardOperationStore(in []*wrappedStandardOperationStore) []anysdk.StandardOperationStore {
	if in == nil {
		return nil
	}
	out := make([]anysdk.StandardOperationStore, 0, len(in))
	for _, v := range in {
		out = append(out, v.inner)
	}
	return out
}

func wrapSlice_View(in []anysdk.View) []View {
	if in == nil {
		return nil
	}
	out := make([]View, 0, len(in))
	for _, v := range in {
		out = append(out, &wrappedView{inner: v})
	}
	return out
}

func unwrapSlice_View(in []View) []anysdk.View {
	if in == nil {
		return nil
	}
	out := make([]anysdk.View, 0, len(in))
	for _, v := range in {
		out = append(out, v.unwrap())
	}
	return out
}

type wrappedPersistenceSystem struct {
	inner persistence.PersistenceSystem
}

func (w *wrappedPersistenceSystem) CacheStoreGet(key string) ([]byte, error) {
	r0, r1 := w.inner.CacheStoreGet(key)
	return r0, r1
}

func (w *wrappedPersistenceSystem) CacheStorePut(key string, value []byte, expiration string, ttl int) error {
	r0 := w.inner.CacheStorePut(key, value, expiration, ttl)
	return r0
}

func (w *wrappedPersistenceSystem) HandleViewCollection(p0 []View) error {
	inner_p0 := unwrapSlice_View(p0)
	r0 := w.inner.HandleViewCollection(inner_p0)
	return r0
}

func (w *wrappedPersistenceSystem) GetSystemName() string {
	r0 := w.inner.GetSystemName()
	return r0
}

func (w *wrappedPersistenceSystem) HandleExternalTables(providerName string, externalTables map[string]SQLExternalTable) error {
	inner_externalTables := make(map[string]anysdk.SQLExternalTable, len(externalTables))
	for k, v := range externalTables {
		inner_externalTables[k] = v.unwrap()
	}
	r0 := w.inner.HandleExternalTables(providerName, inner_externalTables)
	return r0
}

func (w *wrappedPersistenceSystem) unwrap() persistence.PersistenceSystem {
	return w.inner
}

type wrappedAuthMetadata struct {
	inner *anysdk.AuthMetadata
}

func (w *wrappedAuthMetadata) GetHeaders() []string {
	r0 := w.inner.GetHeaders()
	return r0
}

func (w *wrappedAuthMetadata) ToMap() map[string]interface{} {
	r0 := w.inner.ToMap()
	return r0
}

type AuthCtx struct {
	inner *dto.AuthCtx
}

func (w *AuthCtx) Clone() *AuthCtx {
	r0 := w.inner.Clone()
	return &AuthCtx{inner: r0}
}

func (w *AuthCtx) GetCredentialsBytes() ([]byte, error) {
	r0, r1 := w.inner.GetCredentialsBytes()
	return r0, r1
}

func (w *AuthCtx) GetCredentialsSourceDescriptorString() string {
	r0 := w.inner.GetCredentialsSourceDescriptorString()
	return r0
}

func (w *AuthCtx) GetSQLCfg() (SQLBackendCfg, bool) {
	r0, r1 := w.inner.GetSQLCfg()
	return &wrappedSQLBackendCfg{inner: r0}, r1
}

func (w *AuthCtx) HasKey() bool {
	r0 := w.inner.HasKey()
	return r0
}

type wrappedRuntimeCtx struct {
	inner dto.RuntimeCtx
}

func (w *wrappedRuntimeCtx) Copy() RuntimeCtx {
	r0 := w.inner.Copy()
	return &wrappedRuntimeCtx{inner: r0}
}

type wrappedAddressSpaceExpansionConfig struct {
	inner anysdk.AddressSpaceExpansionConfig
}

func (w *wrappedAddressSpaceExpansionConfig) unwrap() anysdk.AddressSpaceExpansionConfig {
	return w.inner
}

func (w *wrappedAddressSpaceExpansionConfig) IsAsync() bool {
	r0 := w.inner.IsAsync()
	return r0
}

func (w *wrappedAddressSpaceExpansionConfig) IsLegacy() bool {
	r0 := w.inner.IsLegacy()
	return r0
}

func (w *wrappedAddressSpaceExpansionConfig) IsAllowNilResponse() bool {
	r0 := w.inner.IsAllowNilResponse()
	return r0
}

type wrappedAddressSpace struct {
	inner anysdk.AddressSpace
}

func (w *wrappedAddressSpace) ToRelation(p0 AddressSpaceExpansionConfig) (Relation, error) {
	r0, r1 := w.inner.ToRelation(p0.unwrap())
	return &wrappedRelation{inner: r0}, r1
}

func (w *wrappedAddressSpace) GetGlobalSelectSchemas() map[string]Schema {
	r0 := w.inner.GetGlobalSelectSchemas()
	rv := make(map[string]Schema, len(r0))
	for k, v := range r0 {
		rv[k] = newWrappedSchemaFromAnySdkSchema(v)
	}
	return rv
}

func (w *wrappedAddressSpace) DereferenceAddress(address string) (any, bool) {
	r0, r1 := w.inner.DereferenceAddress(address)
	return r0, r1
}

func (w *wrappedAddressSpace) WriteToAddress(address string, val any) error {
	r0 := w.inner.WriteToAddress(address, val)
	return r0
}

func (w *wrappedAddressSpace) ReadFromAddress(address string) (any, bool) {
	r0, r1 := w.inner.ReadFromAddress(address)
	return r0, r1
}

func (w *wrappedAddressSpace) ResolveSignature(signature map[string]any) (bool, map[string]any) {
	r0, r1 := w.inner.ResolveSignature(signature)
	return r0, r1
}

func (w *wrappedAddressSpace) Invoke(args ...any) error {
	r0 := w.inner.Invoke(args...)
	return r0
}

func (w *wrappedAddressSpace) ToMap(config AddressSpaceExpansionConfig) (map[string]any, error) {
	r0, r1 := w.inner.ToMap(config)
	return r0, r1
}

func (w *wrappedAddressSpace) unwrap() anysdk.AddressSpace {
	return w.inner
}

func DeprecatedNewAddressable(inner anysdk.Addressable) Addressable {
	return newAddressable(inner)
}

func newAddressable(inner anysdk.Addressable) Addressable {
	return &wrappedAddressable{inner: inner}
}

type Addressable interface {
	ConditionIsValid(lhs string, rhs interface{}) bool
	GetName() string
	GetType() string
}

type wrappedAddressable struct {
	inner anysdk.Addressable
}

func (w *wrappedAddressable) ConditionIsValid(lhs string, rhs interface{}) bool {
	r0 := w.inner.ConditionIsValid(lhs, rhs)
	return r0
}

func (w *wrappedAddressable) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedAddressable) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

type wrappedColumn struct {
	inner anysdk.Column
}

func (w *wrappedColumn) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedColumn) GetSchema() Schema {
	r0 := w.inner.GetSchema()
	return newWrappedSchemaFromAnySdkSchema(r0)
}

func (w *wrappedColumn) GetWidth() int {
	r0 := w.inner.GetWidth()
	return r0
}

type wrappedExpectedRequest struct {
	inner anysdk.ExpectedRequest
}

func (w *wrappedExpectedRequest) GetBodyMediaType() string {
	r0 := w.inner.GetBodyMediaType()
	return r0
}

type wrappedExpectedResponse struct {
	inner anysdk.ExpectedResponse
}

func (w *wrappedExpectedResponse) unwrap() anysdk.ExpectedResponse {
	return w.inner
}

func (w *wrappedExpectedResponse) GetObjectKey() string {
	r0 := w.inner.GetObjectKey()
	return r0
}

func (w *wrappedExpectedResponse) GetTransform() (Transform, bool) {
	r0, r1 := w.inner.GetTransform()
	return &wrappedTransform{inner: r0}, r1
}

type wrappedGraphQL struct {
	inner anysdk.GraphQL
}

func (w *wrappedGraphQL) GetCursorJSONPath() (string, bool) {
	r0, r1 := w.inner.GetCursorJSONPath()
	return r0, r1
}

func (w *wrappedGraphQL) GetQuery() string {
	r0 := w.inner.GetQuery()
	return r0
}

func (w *wrappedGraphQL) GetResponseJSONPath() (string, bool) {
	r0, r1 := w.inner.GetResponseJSONPath()
	return r0, r1
}

func (w *wrappedGraphQL) unwrap() anysdk.GraphQL {
	return w.inner
}

type wrappedHTTPArmoury struct {
	inner anysdk.HTTPArmoury
}

func (w *wrappedHTTPArmoury) GetRequestParams() []HTTPArmouryParameters {
	r0 := w.inner.GetRequestParams()
	return wrapSlice_HTTPArmouryParameters(r0)
}

func (w *wrappedHTTPArmoury) SetRequestParams(p0 []HTTPArmouryParameters) {
	inner_p0 := unwrapSlice_HTTPArmouryParameters(p0)
	w.inner.SetRequestParams(inner_p0)
	return
}

type wrappedHTTPArmouryParameters struct {
	inner anysdk.HTTPArmouryParameters
}

func (w *wrappedHTTPArmouryParameters) Encode() string {
	r0 := w.inner.Encode()
	return r0
}

func (w *wrappedHTTPArmouryParameters) GetArgList() client.AnySdkArgList {
	r0 := w.inner.GetArgList()
	return r0
}

func (w *wrappedHTTPArmouryParameters) GetParameters() HttpParameters {
	r0 := w.inner.GetParameters()
	return &wrappedHttpParameters{inner: r0}
}

func (w *wrappedHTTPArmouryParameters) GetQuery() url.Values {
	r0 := w.inner.GetQuery()
	return r0
}

func (w *wrappedHTTPArmouryParameters) GetRequest() *http.Request {
	r0 := w.inner.GetRequest()
	return r0
}

func (w *wrappedHTTPArmouryParameters) SetNextPage(ops OperationStore, token string, tokenKey HTTPElement) (*http.Request, error) {
	r0, r1 := w.inner.SetNextPage(ops.unwrap(), token, tokenKey)
	return r0, r1
}

func (w *wrappedHTTPArmouryParameters) SetRawQuery(p0 string) {
	w.inner.SetRawQuery(p0)
	return
}

func (w *wrappedHTTPArmouryParameters) ToFlatMap() (map[string]interface{}, error) {
	r0, r1 := w.inner.ToFlatMap()
	return r0, r1
}

type wrappedHTTPPreparator struct {
	inner anysdk.HTTPPreparator
}

func (w *wrappedHTTPPreparator) unwrap() anysdk.HTTPPreparator {
	return w.inner
}

func (w *wrappedHTTPPreparator) BuildHTTPRequestCtx(p0 anysdk.HTTPPreparatorConfig) (HTTPArmoury, error) {
	r0, r1 := w.inner.BuildHTTPRequestCtx(p0)
	return &wrappedHTTPArmoury{inner: r0}, r1
}

type wrappedHttpParameters struct {
	inner anysdk.HttpParameters
}

func (w *wrappedHttpParameters) GetInlineParameterFlatMap() (map[string]interface{}, error) {
	r0, r1 := w.inner.GetInlineParameterFlatMap()
	return r0, r1
}

func (w *wrappedHttpParameters) ToFlatMap() (map[string]interface{}, error) {
	r0, r1 := w.inner.ToFlatMap()
	return r0, r1
}

type wrappedHttpPreparatorStream struct {
	inner anysdk.HttpPreparatorStream
}

func (w *wrappedHttpPreparatorStream) Next() (HTTPPreparator, bool) {
	r0, r1 := w.inner.Next()
	return &wrappedHTTPPreparator{inner: r0}, r1
}

func (w *wrappedHttpPreparatorStream) Write(p0 HTTPPreparator) error {
	r0 := w.inner.Write(p0.unwrap())
	return r0
}

type wrappedITable struct {
	inner anysdk.ITable
}

func (w *wrappedITable) GetKey(p0 string) (interface{}, error) {
	r0, r1 := w.inner.GetKey(p0)
	return r0, r1
}

func (w *wrappedITable) GetKeyAsSqlVal(p0 string) (sqltypes.Value, error) {
	r0, r1 := w.inner.GetKeyAsSqlVal(p0)
	return r0, r1
}

func (w *wrappedITable) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedITable) KeyExists(p0 string) bool {
	r0 := w.inner.KeyExists(p0)
	return r0
}

type wrappedMethodAnalysisOutput struct {
	inner anysdk.MethodAnalysisOutput
}

func (w *wrappedMethodAnalysisOutput) GetInsertTabulation() Tabulation {
	r0 := w.inner.GetInsertTabulation()
	return &wrappedTabulation{inner: r0}
}

func newWrappedSchemaFromAnySdkSchema(inner anysdk.Schema) Schema {
	return &wrappedSchema{inner: inner}
}

func (w *wrappedMethodAnalysisOutput) GetItemSchema() (Schema, bool) {
	r0, r1 := w.inner.GetItemSchema()
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedMethodAnalysisOutput) GetOrderedStarColumnsNames() ([]string, error) {
	r0, r1 := w.inner.GetOrderedStarColumnsNames()
	return r0, r1
}

func (w *wrappedMethodAnalysisOutput) GetSelectTabulation() Tabulation {
	r0 := w.inner.GetSelectTabulation()
	return &wrappedTabulation{inner: r0}
}

func (w *wrappedMethodAnalysisOutput) IsAwait() bool {
	r0 := w.inner.IsAwait()
	return r0
}

func (w *wrappedMethodAnalysisOutput) IsNilResponseAllowed() bool {
	r0 := w.inner.IsNilResponseAllowed()
	return r0
}

type wrappedMethodAnalyzer struct {
	inner anysdk.MethodAnalyzer
}

func (w *wrappedMethodAnalyzer) unwrap() anysdk.MethodAnalyzer {
	return w.inner
}

func (w *wrappedMethodAnalyzer) AnalyzeUnaryAction(p0 anysdk.MethodAnalysisInput) (MethodAnalysisOutput, error) {
	r0, r1 := w.inner.AnalyzeUnaryAction(p0)
	return &wrappedMethodAnalysisOutput{inner: r0}, r1
}

type wrappedMethods struct {
	inner anysdk.Methods
}

func (w *wrappedMethods) unwrap() anysdk.Methods {
	return w.inner
}

func (w *wrappedMethods) OrderMethods() ([]StandardOperationStore, error) {
	r0, r1 := w.inner.OrderMethods()
	return wrapSlice_StandardOperationStore(r0), r1
}

func (w *wrappedMethods) List() []MethodsKV {
	r0, _ := w.inner.OrderMethods()
	result := make([]MethodsKV, len(r0))
	i := 0
	for k, v := range w.inner {
		result[i] = &methodsKv{Key: k, Value: &wrappedStandardOperationStore{inner: &v}}
		i++
	}
	return result
}

func (w *wrappedMethods) Put(k string, v StandardOperationStore) error {
	return w.inner.Put(k, v.unwrapStandardOperationStore())
}

type wrappedOperationInverse struct {
	inner anysdk.OperationInverse
}

func (w *wrappedOperationInverse) GetOperationStore() (StandardOperationStore, bool) {
	r0, r1 := w.inner.GetOperationStore()
	return &wrappedStandardOperationStore{inner: r0}, r1
}

type wrappedOperationStore struct {
	inner anysdk.OperationStore
}

func (w *wrappedOperationStore) IsNullary() bool {
	r0 := w.inner.IsNullary()
	return r0
}

func (w *wrappedOperationStore) GetOptionalParameters() map[string]Addressable {
	r0 := w.inner.GetOptionalParameters()
	return wrapMapString_Addressable(r0)
}

func (w *wrappedOperationStore) GetSelectSchemaAndObjectPath() (Schema, string, error) {
	r0, r1, r2 := w.inner.GetSelectSchemaAndObjectPath()
	return newWrappedSchemaFromAnySdkSchema(r0), r1, r2
}

func (w *wrappedOperationStore) GetResponse() (ExpectedResponse, bool) {
	r0, r1 := w.inner.GetResponse()
	return &wrappedExpectedResponse{inner: r0}, r1
}

func (w *wrappedOperationStore) IsAwaitable() bool {
	r0 := w.inner.IsAwaitable()
	return r0
}

func (w *wrappedOperationStore) GetGraphQL() GraphQL {
	r0 := w.inner.GetGraphQL()
	return &wrappedGraphQL{inner: r0}
}

func (w *wrappedOperationStore) GetAddressSpace() (AddressSpace, bool) {
	r0, r1 := w.inner.GetAddressSpace()
	return &wrappedAddressSpace{inner: r0}, r1
}

func (w *wrappedOperationStore) GetProjections() map[string]string {
	r0 := w.inner.GetProjections()
	return r0
}

func (w *wrappedOperationStore) unwrap() anysdk.OperationStore {
	return w.inner
}

func (w *wrappedOperationStore) DeprecatedProcessResponse(response *http.Response) (map[string]interface{}, error) {
	r0, r1 := w.inner.DeprecatedProcessResponse(response)
	return r0, r1
}

func (w *wrappedOperationStore) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedOperationStore) GetNonBodyParameters() map[string]Addressable {
	r0 := w.inner.GetNonBodyParameters()
	return wrapMapString_Addressable(r0)
}

func (w *wrappedOperationStore) GetPaginationRequestTokenSemantic() (TokenSemantic, bool) {
	r0, r1 := w.inner.GetPaginationRequestTokenSemantic()
	return &wrappedTokenSemantic{inner: r0}, r1
}

func (w *wrappedOperationStore) GetPaginationResponseTokenSemantic() (TokenSemantic, bool) {
	r0, r1 := w.inner.GetPaginationResponseTokenSemantic()
	return &wrappedTokenSemantic{inner: r0}, r1
}

func (w *wrappedOperationStore) GetParameter(paramKey string) (Addressable, bool) {
	r0, r1 := w.inner.GetParameter(paramKey)
	return &wrappedAddressable{inner: r0}, r1
}

func (w *wrappedOperationStore) GetRequestBodySchema() (Schema, error) {
	r0, r1 := w.inner.GetRequestBodySchema()
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedOperationStore) GetRequiredNonBodyParameters() map[string]Addressable {
	r0 := w.inner.GetRequiredNonBodyParameters()
	return wrapMapString_Addressable(r0)
}

func (w *wrappedOperationStore) GetRequiredParameters() map[string]Addressable {
	r0 := w.inner.GetRequiredParameters()
	return wrapMapString_Addressable(r0)
}

func (w *wrappedOperationStore) GetResource() Resource {
	r0 := w.inner.GetResource()
	return &wrappedResource{inner: r0}
}

func (w *wrappedOperationStore) GetResponseBodySchemaAndMediaType() (Schema, string, error) {
	r0, r1, r2 := w.inner.GetResponseBodySchemaAndMediaType()
	return newWrappedSchemaFromAnySdkSchema(r0), r1, r2
}

func (w *wrappedOperationStore) GetSelectItemsKey() string {
	r0 := w.inner.GetSelectItemsKey()
	return r0
}

func (w *wrappedOperationStore) GetService() anysdk.OpenAPIService {
	r0 := w.inner.GetService()
	return r0
}

func (w *wrappedOperationStore) IsRequestBodyAttributeRenamed(p0 string) bool {
	r0 := w.inner.IsRequestBodyAttributeRenamed(p0)
	return r0
}

func (w *wrappedOperationStore) IsRequiredRequestBodyProperty(key string) bool {
	r0 := w.inner.IsRequiredRequestBodyProperty(key)
	return r0
}

func (w *wrappedOperationStore) ProcessResponse(p0 *http.Response) (ProcessedOperationResponse, error) {
	r0, r1 := w.inner.ProcessResponse(p0)
	return &wrappedProcessedOperationResponse{inner: r0}, r1
}

func (w *wrappedOperationStore) RenameRequestBodyAttribute(p0 string) (string, error) {
	r0, r1 := w.inner.RenameRequestBodyAttribute(p0)
	return r0, r1
}

func (w *wrappedOperationStore) RevertRequestBodyAttributeRename(p0 string) (string, error) {
	r0, r1 := w.inner.RevertRequestBodyAttributeRename(p0)
	return r0, r1
}

type wrappedProcessedOperationResponse struct {
	inner anysdk.ProcessedOperationResponse
}

func (w *wrappedProcessedOperationResponse) GetResponse() (Response, bool) {
	r0, r1 := w.inner.GetResponse()
	return &wrappedResponse{inner: r0}, r1
}

func (w *wrappedProcessedOperationResponse) GetReversal() (HTTPPreparator, bool) {
	r0, r1 := w.inner.GetReversal()
	return &wrappedHTTPPreparator{inner: r0}, r1
}

type wrappedExecContext struct {
	inner anysdk.ExecContext
}

func (w *wrappedExecContext) GetExecPayload() internaldto.ExecPayload {
	r0 := w.inner.GetExecPayload()
	return r0
}

func (w *wrappedExecContext) GetResource() Resource {
	r0 := w.inner.GetResource()
	return &wrappedResource{inner: r0}
}

func (w *wrappedExecContext) unwrap() anysdk.ExecContext {
	return w.inner
}

type wrappedProvider struct {
	inner anysdk.Provider
}

func (w *wrappedProvider) unwrap() anysdk.Provider {
	return w.inner
}

func (w *wrappedProvider) GetAuth() (AuthDTO, bool) {
	r0, r1 := w.inner.GetAuth()
	return &wrappedAuthDTO{inner: r0}, r1
}

func (w *wrappedProvider) GetDeleteItemsKey() string {
	r0 := w.inner.GetDeleteItemsKey()
	return r0
}

func (w *wrappedProvider) GetMinStackQLVersion() string {
	r0 := w.inner.GetMinStackQLVersion()
	return r0
}

func (w *wrappedProvider) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedProvider) GetProtocolType() (client.ClientProtocolType, error) {
	r0, r1 := w.inner.GetProtocolType()
	return r0, r1
}

type wrappedProviderDescription struct {
	inner anysdk.ProviderDescription
}

func (w *wrappedProviderDescription) GetLatestVersion() (string, error) {
	r0, r1 := w.inner.GetLatestVersion()
	return r0, r1
}

func (w *wrappedProviderDescription) Versions() []string {
	r0 := w.inner.Versions
	return r0
}

type wrappedProviderService struct {
	inner anysdk.ProviderService
}

func (w *wrappedProviderService) GetKey(p0 string) (interface{}, error) {
	r0, r1 := w.inner.GetKey(p0)
	return r0, r1
}

func (w *wrappedProviderService) GetKeyAsSqlVal(p0 string) (sqltypes.Value, error) {
	r0, r1 := w.inner.GetKeyAsSqlVal(p0)
	return r0, r1
}

func (w *wrappedProviderService) KeyExists(p0 string) bool {
	r0 := w.inner.KeyExists(p0)
	return r0
}

func (w *wrappedProviderService) unwrap() anysdk.ProviderService {
	return w.inner
}

func (w *wrappedProviderService) GetDescription() string {
	r0 := w.inner.GetDescription()
	return r0
}

func (w *wrappedProviderService) GetID() string {
	r0 := w.inner.GetID()
	return r0
}

func (w *wrappedProviderService) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedProviderService) GetTitle() string {
	r0 := w.inner.GetTitle()
	return r0
}

func (w *wrappedProviderService) GetVersion() string {
	r0 := w.inner.GetVersion()
	return r0
}

func (w *wrappedProviderService) IsPreferred() bool {
	r0 := w.inner.IsPreferred()
	return r0
}

type wrappedRegistryAPI struct {
	inner anysdk.RegistryAPI
}

func (w *wrappedRegistryAPI) unwrap() anysdk.RegistryAPI {
	return w.inner
}

func (w *wrappedRegistryAPI) ClearProviderCache(p0 string) error {
	r0 := w.inner.ClearProviderCache(p0)
	return r0
}

func (w *wrappedRegistryAPI) GetLatestPublishedVersion(p0 string) (string, error) {
	r0, r1 := w.inner.GetLatestPublishedVersion(p0)
	return r0, r1
}

func (w *wrappedRegistryAPI) ListAllAvailableProviders() (map[string]ProviderDescription, error) {
	r0, r1 := w.inner.ListAllAvailableProviders()
	return wrapMapString_ProviderDescription(r0), r1
}

func (w *wrappedRegistryAPI) ListAllProviderVersions(p0 string) (map[string]ProviderDescription, error) {
	r0, r1 := w.inner.ListAllProviderVersions(p0)
	return wrapMapString_ProviderDescription(r0), r1
}

func (w *wrappedRegistryAPI) ListLocallyAvailableProviders() map[string]ProviderDescription {
	r0 := w.inner.ListLocallyAvailableProviders()
	return wrapMapString_ProviderDescription(r0)
}

func (w *wrappedRegistryAPI) LoadProviderByName(p0 string, p1 string) (Provider, error) {
	r0, r1 := w.inner.LoadProviderByName(p0, p1)
	return &wrappedProvider{inner: r0}, r1
}

func (w *wrappedRegistryAPI) PullAndPersistProviderArchive(p0 string, p1 string) error {
	r0 := w.inner.PullAndPersistProviderArchive(p0, p1)
	return r0
}

func (w *wrappedRegistryAPI) RemoveProviderVersion(p0 string, p1 string) error {
	r0 := w.inner.RemoveProviderVersion(p0, p1)
	return r0
}

type wrappedRelation struct {
	inner anysdk.Relation
}

func (w *wrappedRelation) GetColumnDescriptors() []ColumnDescriptor {
	r0 := w.inner.GetColumnDescriptors()
	rv := make([]ColumnDescriptor, len(r0))
	for i, v := range r0 {
		rv[i] = &wrappedColumnDescriptor{inner: v}
	}
	return rv
}

func (w *wrappedRelation) GetColumns() []Column {
	r0 := w.inner.GetColumns()
	return wrapSlice_Column(r0)
}

type wrappedResource struct {
	inner anysdk.Resource
}

func (w *wrappedResource) GetKey(p0 string) (interface{}, error) {
	r0, r1 := w.inner.GetKey(p0)
	return r0, r1
}

func (w *wrappedResource) GetKeyAsSqlVal(p0 string) (sqltypes.Value, error) {
	r0, r1 := w.inner.GetKeyAsSqlVal(p0)
	return r0, r1
}

func (w *wrappedResource) KeyExists(p0 string) bool {
	r0 := w.inner.KeyExists(p0)
	return r0
}

func (w *wrappedResource) unwrap() anysdk.Resource {
	return w.inner
}

func (w *wrappedResource) FindMethod(key string) (StandardOperationStore, error) {
	r0, r1 := w.inner.FindMethod(key)
	return &wrappedStandardOperationStore{inner: r0}, r1
}

func (w *wrappedResource) GetFirstMethodFromSQLVerb(sqlVerb string) (StandardOperationStore, string, bool) {
	r0, r1, r2 := w.inner.GetFirstMethodFromSQLVerb(sqlVerb)
	return &wrappedStandardOperationStore{inner: r0}, r1, r2
}

func (w *wrappedResource) GetFirstNamespaceMethodMatchFromSQLVerb(sqlVerb string, parameters map[string]interface{}) (StandardOperationStore, map[string]interface{}, bool) {
	r0, r1, r2 := w.inner.GetFirstNamespaceMethodMatchFromSQLVerb(sqlVerb, parameters)
	return &wrappedStandardOperationStore{inner: r0}, r1, r2
}

func (w *wrappedResource) GetID() string {
	r0 := w.inner.GetID()
	return r0
}

func (w *wrappedResource) GetMethodsMatched() Methods {
	r0 := w.inner.GetMethodsMatched()
	return &wrappedMethods{inner: r0}
}

func (w *wrappedResource) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedResource) GetViewsForSqlDialect(sqlDialect string) ([]View, bool) {
	r0, r1 := w.inner.GetViewsForSqlDialect(sqlDialect)
	return wrapSlice_View(r0), r1
}

func (w *wrappedResource) ToMap(extended bool) map[string]interface{} {
	r0 := w.inner.ToMap(extended)
	return r0
}

type wrappedSQLExternalColumn struct {
	inner anysdk.SQLExternalColumn
}

func (w *wrappedSQLExternalColumn) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedSQLExternalColumn) GetOid() uint32 {
	r0 := w.inner.GetOid()
	return r0
}

func (w *wrappedSQLExternalColumn) GetPrecision() int {
	r0 := w.inner.GetPrecision()
	return r0
}

func (w *wrappedSQLExternalColumn) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

func (w *wrappedSQLExternalColumn) GetWidth() int {
	r0 := w.inner.GetWidth()
	return r0
}

type wrappedSQLExternalTable struct {
	inner anysdk.SQLExternalTable
}

func (w *wrappedSQLExternalTable) GetCatalogName() string {
	r0 := w.inner.GetCatalogName()
	return r0
}

func (w *wrappedSQLExternalTable) GetColumns() []SQLExternalColumn {
	r0 := w.inner.GetColumns()
	return wrapSlice_SQLExternalColumn(r0)
}

func (w *wrappedSQLExternalTable) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedSQLExternalTable) GetSchemaName() string {
	r0 := w.inner.GetSchemaName()
	return r0
}

func (w *wrappedSQLExternalTable) unwrap() anysdk.SQLExternalTable {
	return w.inner
}

type wrappedSchema struct {
	inner anysdk.Schema
}

func (w *wrappedSchema) unwrap() anysdk.Schema {
	return w.inner
}

func (w *wrappedSchema) FindByPath(path string, visited map[string]bool) Schema {
	r0 := w.inner.FindByPath(path, visited)
	return newWrappedSchemaFromAnySdkSchema(r0)
}

func (w *wrappedSchema) GetAdditionalProperties() (Schema, bool) {
	r0, r1 := w.inner.GetAdditionalProperties()
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedSchema) GetAllColumns(p0 string) []string {
	r0 := w.inner.GetAllColumns(p0)
	return r0
}

func (w *wrappedSchema) GetItemsSchema() (Schema, error) {
	r0, r1 := w.inner.GetItemsSchema()
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedSchema) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedSchema) GetProperties() (Schemas, error) {
	r0, r1 := w.inner.GetProperties()
	if r1 != nil {
		return nil, r1
	}
	rv := make(Schemas, len(r0))
	for k, v := range r0 {
		rv[k] = newWrappedSchemaFromAnySdkSchema(v)
	}
	return rv, nil
}

func (w *wrappedSchema) GetProperty(propertyKey string) (Schema, bool) {
	r0, r1 := w.inner.GetProperty(propertyKey)
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedSchema) GetPropertySchema(key string) (Schema, error) {
	r0, r1 := w.inner.GetPropertySchema(key)
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedSchema) GetSelectSchema(itemsKey string, mediaType string) (Schema, string, error) {
	r0, r1, r2 := w.inner.GetSelectSchema(itemsKey, mediaType)
	return newWrappedSchemaFromAnySdkSchema(r0), r1, r2
}

func (w *wrappedSchema) GetSelectionName() string {
	r0 := w.inner.GetSelectionName()
	return r0
}

func (w *wrappedSchema) GetTitle() string {
	r0 := w.inner.GetTitle()
	return r0
}

func (w *wrappedSchema) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

func (w *wrappedSchema) IsBoolean() bool {
	r0 := w.inner.IsBoolean()
	return r0
}

func (w *wrappedSchema) IsFloat() bool {
	r0 := w.inner.IsFloat()
	return r0
}

func (w *wrappedSchema) IsIntegral() bool {
	r0 := w.inner.IsIntegral()
	return r0
}

func (w *wrappedSchema) IsReadOnly() bool {
	r0 := w.inner.IsReadOnly()
	return r0
}

func (w *wrappedSchema) IsRequired(key string) bool {
	r0 := w.inner.IsRequired(key)
	return r0
}

func (w *wrappedSchema) SetKey(p0 string) {
	w.inner.SetKey(p0)
	return
}

func (w *wrappedSchema) Tabulate(p0 bool, p1 string) Tabulation {
	r0 := w.inner.Tabulate(p0, p1)
	return &wrappedTabulation{inner: r0}
}

func (w *wrappedSchema) ToDescriptionMap(extended bool) map[string]interface{} {
	r0 := w.inner.ToDescriptionMap(extended)
	return r0
}

type wrappedService struct {
	inner anysdk.Service
}

func (w *wrappedService) unwrap() anysdk.Service {
	return w.inner
}

func (w *wrappedService) GetResource(resourceName string) (Resource, error) {
	r0, r1 := w.inner.GetResource(resourceName)
	return &wrappedResource{inner: r0}, r1
}

func (w *wrappedService) GetSchema(key string) (Schema, error) {
	r0, r1 := w.inner.GetSchema(key)
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedService) GetServers() (openapi3.Servers, bool) {
	r0, r1 := w.inner.GetServers()
	return r0, r1
}

var (
	_ ITable = (*wrappedStandardOperationStore)(nil)
)

type wrappedStandardOperationStore struct {
	inner anysdk.StandardOperationStore
}

func (w *wrappedStandardOperationStore) GetInline() []string {
	r0 := w.inner.GetInline()
	return r0
}

func (w *wrappedStandardOperationStore) GetRequest() (ExpectedRequest, bool) {
	r0, r1 := w.inner.GetRequest()
	return &wrappedExpectedRequest{inner: r0}, r1
}

func (w *wrappedStandardOperationStore) IsNullary() bool {
	r0 := w.inner.IsNullary()
	return r0
}

func (w *wrappedStandardOperationStore) GetColumnOrder(extended bool) []string {
	r0 := w.inner.GetColumnOrder(extended)
	return r0
}

func (w *wrappedStandardOperationStore) ToPresentationMap(extended bool) map[string]interface{} {
	r0 := w.inner.ToPresentationMap(extended)
	return r0
}

func (w *wrappedStandardOperationStore) GetKey(s string) (interface{}, error) {
	r0, r1 := w.inner.GetKey(s)
	return r0, r1
}

func (w *wrappedStandardOperationStore) GetKeyAsSqlVal(p0 string) (sqltypes.Value, error) {
	r0, r1 := w.inner.GetKeyAsSqlVal(p0)
	return r0, r1
}

func (w *wrappedStandardOperationStore) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedStandardOperationStore) KeyExists(p0 string) bool {
	r0 := w.inner.KeyExists(p0)
	return r0
}

func (w *wrappedStandardOperationStore) GetOptionalParameters() map[string]Addressable {
	r0 := w.inner.GetOptionalParameters()
	return wrapMapString_Addressable(r0)
}

func (w *wrappedStandardOperationStore) GetSelectSchemaAndObjectPath() (Schema, string, error) {
	r0, r1, r2 := w.inner.GetSelectSchemaAndObjectPath()
	return newWrappedSchemaFromAnySdkSchema(r0), r1, r2
}

func (w *wrappedStandardOperationStore) GetResponse() (ExpectedResponse, bool) {
	r0, r1 := w.inner.GetResponse()
	return &wrappedExpectedResponse{inner: r0}, r1
}

func (w *wrappedStandardOperationStore) IsAwaitable() bool {
	r0 := w.inner.IsAwaitable()
	return r0
}

func (w *wrappedStandardOperationStore) GetGraphQL() GraphQL {
	r0 := w.inner.GetGraphQL()
	return &wrappedGraphQL{inner: r0}
}

func (w *wrappedStandardOperationStore) GetAddressSpace() (AddressSpace, bool) {
	r0, r1 := w.inner.GetAddressSpace()
	return &wrappedAddressSpace{inner: r0}, r1
}

func (w *wrappedStandardOperationStore) GetProjections() map[string]string {
	r0 := w.inner.GetProjections()
	return r0
}

func (w *wrappedStandardOperationStore) GetServers() (openapi3.Servers, bool) {
	r0, r1 := w.inner.GetServers()
	return r0, r1
}

func (w *wrappedStandardOperationStore) unwrap() anysdk.OperationStore {
	return w.inner
}

func (w *wrappedStandardOperationStore) unwrapStandardOperationStore() anysdk.StandardOperationStore {
	return w.inner
}

func (w *wrappedStandardOperationStore) DeprecatedProcessResponse(response *http.Response) (map[string]interface{}, error) {
	r0, r1 := w.inner.DeprecatedProcessResponse(response)
	return r0, r1
}

func (w *wrappedStandardOperationStore) GetNonBodyParameters() map[string]Addressable {
	r0 := w.inner.GetNonBodyParameters()
	return wrapMapString_Addressable(r0)
}

func (w *wrappedStandardOperationStore) GetPaginationRequestTokenSemantic() (TokenSemantic, bool) {
	r0, r1 := w.inner.GetPaginationRequestTokenSemantic()
	return &wrappedTokenSemantic{inner: r0}, r1
}

func (w *wrappedStandardOperationStore) GetPaginationResponseTokenSemantic() (TokenSemantic, bool) {
	r0, r1 := w.inner.GetPaginationResponseTokenSemantic()
	return &wrappedTokenSemantic{inner: r0}, r1
}

func (w *wrappedStandardOperationStore) GetParameter(paramKey string) (Addressable, bool) {
	r0, r1 := w.inner.GetParameter(paramKey)
	return &wrappedAddressable{inner: r0}, r1
}

func (w *wrappedStandardOperationStore) GetRequestBodySchema() (Schema, error) {
	r0, r1 := w.inner.GetRequestBodySchema()
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedStandardOperationStore) GetRequiredNonBodyParameters() map[string]Addressable {
	r0 := w.inner.GetRequiredNonBodyParameters()
	return wrapMapString_Addressable(r0)
}

func (w *wrappedStandardOperationStore) GetRequiredParameters() map[string]Addressable {
	r0 := w.inner.GetRequiredParameters()
	return wrapMapString_Addressable(r0)
}

func (w *wrappedStandardOperationStore) GetResource() Resource {
	r0 := w.inner.GetResource()
	return &wrappedResource{inner: r0}
}

func (w *wrappedStandardOperationStore) GetResponseBodySchemaAndMediaType() (Schema, string, error) {
	r0, r1, r2 := w.inner.GetResponseBodySchemaAndMediaType()
	return newWrappedSchemaFromAnySdkSchema(r0), r1, r2
}

func (w *wrappedStandardOperationStore) GetSelectItemsKey() string {
	r0 := w.inner.GetSelectItemsKey()
	return r0
}

func (w *wrappedStandardOperationStore) GetService() OpenAPIService {
	r0 := w.inner.GetService()
	return &wrappedOpenAPIService{inner: r0}
}

func (w *wrappedStandardOperationStore) IsRequestBodyAttributeRenamed(p0 string) bool {
	r0 := w.inner.IsRequestBodyAttributeRenamed(p0)
	return r0
}

func (w *wrappedStandardOperationStore) IsRequiredRequestBodyProperty(key string) bool {
	r0 := w.inner.IsRequiredRequestBodyProperty(key)
	return r0
}

func (w *wrappedStandardOperationStore) ProcessResponse(p0 *http.Response) (ProcessedOperationResponse, error) {
	r0, r1 := w.inner.ProcessResponse(p0)
	return &wrappedProcessedOperationResponse{inner: r0}, r1
}

func (w *wrappedStandardOperationStore) RenameRequestBodyAttribute(p0 string) (string, error) {
	r0, r1 := w.inner.RenameRequestBodyAttribute(p0)
	return r0, r1
}

func (w *wrappedStandardOperationStore) RevertRequestBodyAttributeRename(p0 string) (string, error) {
	r0, r1 := w.inner.RevertRequestBodyAttributeRename(p0)
	return r0, r1
}

type wrappedTabulation struct {
	inner anysdk.Tabulation
}

func (w *wrappedTabulation) GetColumns() []ColumnDescriptor {
	r0 := w.inner.GetColumns()
	rv := make([]ColumnDescriptor, len(r0))
	for i, v := range r0 {
		rv[i] = &wrappedColumnDescriptor{inner: v}
	}
	return rv
}

func (w *wrappedTabulation) PushBackColumn(col ColumnDescriptor) {
	w.inner.PushBackColumn(col.unwrap())
	return
}

func (w *wrappedTabulation) RenameColumnsToXml() Tabulation {
	r0 := w.inner.RenameColumnsToXml()
	return &wrappedTabulation{inner: r0}
}

type wrappedTokenSemantic struct {
	inner anysdk.TokenSemantic
}

func (w *wrappedTokenSemantic) GetKey() string {
	r0 := w.inner.GetKey()
	return r0
}

func (w *wrappedTokenSemantic) GetLocation() string {
	r0 := w.inner.GetLocation()
	return r0
}

func (w *wrappedTokenSemantic) GetTransformer() (TokenTransformer, error) {
	r0, r1 := w.inner.GetTransformer()
	return TokenTransformer(r0), r1
}

type wrappedTransform struct {
	inner anysdk.Transform
}

func (w *wrappedTransform) GetBody() string {
	r0 := w.inner.GetBody()
	return r0
}

func (w *wrappedTransform) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

type wrappedView struct {
	inner anysdk.View
}

func (w *wrappedView) GetDDL() string {
	r0 := w.inner.GetDDL()
	return r0
}

func (w *wrappedView) GetNameNaive() string {
	r0 := w.inner.GetNameNaive()
	return r0
}

func (w *wrappedView) GetRequiredParamNames() []string {
	r0 := w.inner.GetRequiredParamNames()
	return r0
}

func (w *wrappedView) unwrap() anysdk.View {
	return w.inner
}

type wrappedAuthUtility struct {
	inner auth_util.AuthUtility
}

func (w *wrappedAuthUtility) ActivateAuth(authCtx *AuthCtx, principal string, authType string) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	w.inner.ActivateAuth(inner_authCtx, principal, authType)
	return
}

func (w *wrappedAuthUtility) ApiTokenAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext, enforceBearer bool) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.ApiTokenAuth(inner_authCtx, httpContext, enforceBearer)
	return r0, r1
}

func (w *wrappedAuthUtility) AuthRevoke(authCtx *AuthCtx) error {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0 := w.inner.AuthRevoke(inner_authCtx)
	return r0
}

func (w *wrappedAuthUtility) AwsSigningAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.AwsSigningAuth(inner_authCtx, httpContext)
	return r0, r1
}

func (w *wrappedAuthUtility) AzureDefaultAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.AzureDefaultAuth(inner_authCtx, httpContext)
	return r0, r1
}

func (w *wrappedAuthUtility) BasicAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.BasicAuth(inner_authCtx, httpContext)
	return r0, r1
}

func (w *wrappedAuthUtility) CustomAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.CustomAuth(inner_authCtx, httpContext)
	return r0, r1
}

func (w *wrappedAuthUtility) GCloudOAuth(runtimeCtx RuntimeCtx, authCtx *AuthCtx, enforceRevokeFirst bool) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	wrappedRuntimeCtx, isWrapped := runtimeCtx.(*wrappedRuntimeCtx)
	if !isWrapped {
		return nil, fmt.Errorf("invalid RuntimeCtx type: expected *wrappedRuntimeCtx, got %T", runtimeCtx)
	}
	r0, r1 := w.inner.GCloudOAuth(wrappedRuntimeCtx.inner, inner_authCtx, enforceRevokeFirst)
	return r0, r1
}

func (w *wrappedAuthUtility) GenericOauthClientCredentials(authCtx *AuthCtx, scopes []string, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.GenericOauthClientCredentials(inner_authCtx, scopes, httpContext)
	return r0, r1
}

func (w *wrappedAuthUtility) GetCurrentGCloudOauthUser() ([]byte, error) {
	r0, r1 := w.inner.GetCurrentGCloudOauthUser()
	return r0, r1
}

func (w *wrappedAuthUtility) GoogleOauthServiceAccount(provider string, authCtx *AuthCtx, scopes []string, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.GoogleOauthServiceAccount(provider, inner_authCtx, scopes, httpContext)
	return r0, r1
}

func (w *wrappedAuthUtility) ParseServiceAccountFile(ac *AuthCtx) (any, error) {
	var inner_ac *dto.AuthCtx
	if ac != nil {
		inner_ac = ac.inner
	}
	r0, r1 := w.inner.ParseServiceAccountFile(inner_ac)
	return r0, r1
}

type wrappedAnySdkClientConfigurator struct {
	inner client.AnySdkClientConfigurator
}

func (w *wrappedAnySdkClientConfigurator) Auth(authCtx *AuthCtx, authTypeRequested string, enforceRevokeFirst bool) (client.AnySdkClient, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.Auth(inner_authCtx, authTypeRequested, enforceRevokeFirst)
	return r0, r1
}

type wrappedAnySdkResponse struct {
	inner client.AnySdkResponse
}

func (w *wrappedAnySdkResponse) GetHttpResponse() (*http.Response, error) {
	r0, r1 := w.inner.GetHttpResponse()
	return r0, r1
}

type wrappedControlAttributes struct {
	inner sqlcontrol.ControlAttributes
}

func (w *wrappedControlAttributes) GetControlGCStatusColumnName() string {
	r0 := w.inner.GetControlGCStatusColumnName()
	return r0
}

func (w *wrappedControlAttributes) GetControlGenIDColumnName() string {
	r0 := w.inner.GetControlGenIDColumnName()
	return r0
}

func (w *wrappedControlAttributes) GetControlInsIDColumnName() string {
	r0 := w.inner.GetControlInsIDColumnName()
	return r0
}

func (w *wrappedControlAttributes) GetControlInsertEncodedIDColumnName() string {
	r0 := w.inner.GetControlInsertEncodedIDColumnName()
	return r0
}

func (w *wrappedControlAttributes) GetControlLatestUpdateColumnName() string {
	r0 := w.inner.GetControlLatestUpdateColumnName()
	return r0
}

func (w *wrappedControlAttributes) GetControlMaxTxnColumnName() string {
	r0 := w.inner.GetControlMaxTxnColumnName()
	return r0
}

func (w *wrappedControlAttributes) GetControlSsnIDColumnName() string {
	r0 := w.inner.GetControlSsnIDColumnName()
	return r0
}

func (w *wrappedControlAttributes) GetControlTxnIDColumnName() string {
	r0 := w.inner.GetControlTxnIDColumnName()
	return r0
}

type wrappedAuthContexts struct {
	inner dto.AuthContexts
}

func (w *wrappedAuthContexts) Clone() AuthContexts {
	r0 := w.inner.Clone()
	return &wrappedAuthContexts{inner: r0}
}

type wrappedDataFlowCfg struct {
	inner dto.DataFlowCfg
}

func (w *wrappedDataFlowCfg) GetMaxDependencies() int {
	r0 := w.inner.GetMaxDependencies()
	return r0
}

type wrappedNamespaceCfg struct {
	inner dto.NamespaceCfg
}

func (w *wrappedNamespaceCfg) GetRegex() (*regexp.Regexp, error) {
	r0, r1 := w.inner.GetRegex()
	return r0, r1
}

func (w *wrappedNamespaceCfg) GetTemplate() (*template.Template, error) {
	r0, r1 := w.inner.GetTemplate()
	return r0, r1
}

type wrappedOutputPacket struct {
	inner dto.OutputPacket
}

func (w *wrappedOutputPacket) GetColumnNames() []string {
	r0 := w.inner.GetColumnNames()
	return r0
}

func (w *wrappedOutputPacket) GetColumnOIDs() []oid.Oid {
	r0 := w.inner.GetColumnOIDs()
	return r0
}

func (w *wrappedOutputPacket) GetRawRows() map[int]map[int]interface{} {
	r0 := w.inner.GetRawRows()
	return r0
}

func (w *wrappedOutputPacket) GetRows() map[string]map[string]interface{} {
	r0 := w.inner.GetRows()
	return r0
}

type wrappedPgTLSCfg struct {
	inner dto.PgTLSCfg
}

func (w *wrappedPgTLSCfg) GetKeyPair() (tls.Certificate, error) {
	r0, r1 := w.inner.GetKeyPair()
	return r0, r1
}

type wrappedSQLBackendCfg struct {
	inner dto.SQLBackendCfg
}

func (w *wrappedSQLBackendCfg) GetDatabaseName() (string, error) {
	r0, r1 := w.inner.GetDatabaseName()
	return r0, r1
}

func (w *wrappedSQLBackendCfg) GetIntelViewSchemaName() string {
	r0 := w.inner.GetIntelViewSchemaName()
	return r0
}

func (w *wrappedSQLBackendCfg) GetOpsViewSchemaName() string {
	r0 := w.inner.GetOpsViewSchemaName()
	return r0
}

func (w *wrappedSQLBackendCfg) GetSQLDialect() string {
	r0 := w.inner.GetSQLDialect()
	return r0
}

func (w *wrappedSQLBackendCfg) GetSchemaType() string {
	r0 := w.inner.GetSchemaType()
	return r0
}

func (w *wrappedSQLBackendCfg) GetTableSchemaName() string {
	r0 := w.inner.GetTableSchemaName()
	return r0
}

type wrappedSessionContext struct {
	inner dto.SessionContext
}

func (w *wrappedSessionContext) GetIsolationLevel() constants.IsolationLevel {
	r0 := w.inner.GetIsolationLevel()
	return r0
}

func (w *wrappedSessionContext) GetRollbackType() constants.RollbackType {
	r0 := w.inner.GetRollbackType()
	return r0
}

func (w *wrappedSessionContext) UpdateIsolationLevel(p0 string) error {
	r0 := w.inner.UpdateIsolationLevel(p0)
	return r0
}

type wrappedTxnCoordinatorCfg struct {
	inner dto.TxnCoordinatorCfg
}

func (w *wrappedTxnCoordinatorCfg) GetMaxTxnDepth() int {
	r0 := w.inner.GetMaxTxnDepth()
	return r0
}

type wrappedGQLReader struct {
	inner graphql.GQLReader
}

func (w *wrappedGQLReader) Read() ([]map[string]interface{}, error) {
	r0, r1 := w.inner.Read()
	return r0, r1
}

type wrappedExecPayload struct {
	inner internaldto.ExecPayload
}

func (w *wrappedExecPayload) GetPayloadMap() map[string]interface{} {
	r0 := w.inner.GetPayloadMap()
	return r0
}

type wrappedHTTPElement struct {
	inner internaldto.HTTPElement
}

func (w *wrappedHTTPElement) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedHTTPElement) GetType() internaldto.HTTPElementType {
	r0 := w.inner.GetType()
	return r0
}

func (w *wrappedHTTPElement) SetTransformer(transformer func(interface{}) (interface{}, error)) {
	w.inner.SetTransformer(transformer)
	return
}

func (w *wrappedHTTPElement) IsTransformerPresent() bool {
	r0 := w.inner.IsTransformerPresent()
	return r0
}

func (w *wrappedHTTPElement) Transformer(t interface{}) (interface{}, error) {
	r0, r1 := w.inner.Transformer(t)
	return r0, r1
}

type wrappedExecutionResponse struct {
	inner local_template_executor.ExecutionResponse
}

func (w *wrappedExecutionResponse) GetStdErr() (*bytes.Buffer, bool) {
	r0, r1 := w.inner.GetStdErr()
	return r0, r1
}

func (w *wrappedExecutionResponse) GetStdOut() (*bytes.Buffer, bool) {
	r0, r1 := w.inner.GetStdOut()
	return r0, r1
}

type wrappedExecutor struct {
	inner local_template_executor.Executor
}

func (w *wrappedExecutor) Execute(p0 map[string]any) (ExecutionResponse, error) {
	r0, r1 := w.inner.Execute(p0)
	return &wrappedExecutionResponse{inner: r0}, r1
}

type wrappedNameMangler struct {
	inner name_mangle.NameMangler
}

func (w *wrappedNameMangler) MangleName(p0 string, p1 ...any) string {
	r0 := w.inner.MangleName(p0, p1)
	return r0
}

type httpActionInsertPayload struct {
	itemisationResult providerinvoker.ItemisationResult
	housekeepingDone  bool
	tableName         string
	paramsUsed        map[string]interface{}
	reqEncoding       string
}

func (ap *httpActionInsertPayload) GetItemisationResult() providerinvoker.ItemisationResult {
	return ap.itemisationResult
}

func (ap *httpActionInsertPayload) IsHousekeepingDone() bool {
	return ap.housekeepingDone
}

func (ap *httpActionInsertPayload) GetTableName() string {
	return ap.tableName
}

func (ap *httpActionInsertPayload) GetParamsUsed() map[string]interface{} {
	return ap.paramsUsed
}

func (ap *httpActionInsertPayload) GetReqEncoding() string {
	return ap.reqEncoding
}

type wrappedActionInsertPayload struct {
	inner providerinvoker.ActionInsertPayload
}

func (w *wrappedActionInsertPayload) GetItemisationResult() ItemisationResult {
	r0 := w.inner.GetItemisationResult()
	return &wrappedItemisationResult{inner: r0}
}

func (w *wrappedActionInsertPayload) GetParamsUsed() map[string]interface{} {
	r0 := w.inner.GetParamsUsed()
	return r0
}

func (w *wrappedActionInsertPayload) GetReqEncoding() string {
	r0 := w.inner.GetReqEncoding()
	return r0
}

func (w *wrappedActionInsertPayload) GetTableName() string {
	r0 := w.inner.GetTableName()
	return r0
}

func (w *wrappedActionInsertPayload) IsHousekeepingDone() bool {
	r0 := w.inner.IsHousekeepingDone()
	return r0
}

type wrappedActionInsertResult struct {
	inner providerinvoker.ActionInsertResult
}

func (w *wrappedActionInsertResult) GetError() (error, bool) {
	r0, r1 := w.inner.GetError()
	return r0, r1
}

func (w *wrappedActionInsertResult) IsHousekeepingDone() bool {
	r0 := w.inner.IsHousekeepingDone()
	return r0
}

type wrappedInsertPreparator struct {
	inner providerinvoker.InsertPreparator
}

func (w *wrappedInsertPreparator) unwrap() providerinvoker.InsertPreparator {
	return w.inner
}

func (w *wrappedInsertPreparator) ActionInsertPreparation(payload *wrappedActionInsertPayload) ActionInsertResult {
	r0 := w.inner.ActionInsertPreparation(payload.inner)
	return &wrappedActionInsertResult{inner: r0}
}

type wrappedInvoker struct {
	inner providerinvoker.Invoker
}

func (w *wrappedInvoker) Invoke(ctx context.Context, req providerinvoker.Request) (providerinvoker.Result, error) {
	r0, r1 := w.inner.Invoke(ctx, req)
	return r0, r1
}

type wrappedItemisationResult struct {
	inner providerinvoker.ItemisationResult
}

func (w *wrappedItemisationResult) GetItems() (interface{}, bool) {
	r0, r1 := w.inner.GetItems()
	return r0, r1
}

/*
GetSingltetonResponse() (map[string]interface{}, bool)
	IsOk() bool
	IsNilPayload() bool
*/

func (w *wrappedItemisationResult) GetSingltetonResponse() (map[string]interface{}, bool) {
	r0, r1 := w.inner.GetSingltetonResponse()
	return r0, r1
}

func (w *wrappedItemisationResult) IsOk() bool {
	r0 := w.inner.IsOk()
	return r0
}

func (w *wrappedItemisationResult) IsNilPayload() bool {
	r0 := w.inner.IsNilPayload()
	return r0
}

type wrappedResponse struct {
	inner response.Response
}

func (w *wrappedResponse) Error() string {
	r0 := w.inner.Error()
	return r0
}

// type HTTPElement interface {
// 	GetName() string
// 	GetLocation() HTTPElementLocation
// }

type wrappedHTTPHTTPElement struct {
	inner httpelement.HTTPElement
}

func (w *wrappedHTTPHTTPElement) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedHTTPHTTPElement) GetLocation() httpelement.HTTPElementLocation {
	r0 := w.inner.GetLocation()
	return r0
}

// TODO: fix this crap
func (w *wrappedResponse) ExtractElement(e HTTPHTTPElement) (interface{}, error) {
	if innerElement, ok := e.(*wrappedHTTPHTTPElement); ok {
		return w.inner.ExtractElement(innerElement.inner)
	}
	return nil, fmt.Errorf("invalid HTTP element type: expected *wrappedHTTPHTTPElement, got %T", e)
}

func (w *wrappedResponse) GetHttpResponse() *http.Response {
	r0 := w.inner.GetHttpResponse()
	return r0
}

func (w *wrappedResponse) GetProcessedBody() interface{} {
	r0 := w.inner.GetProcessedBody()
	return r0
}

func (w *wrappedResponse) HasError() bool {
	r0 := w.inner.HasError()
	return r0
}

type wrappedStreamTransformer struct {
	inner stream_transform.StreamTransformer
}

func (w *wrappedStreamTransformer) GetOutStream() io.Reader {
	r0 := w.inner.GetOutStream()
	return r0
}

func (w *wrappedStreamTransformer) Transform() error {
	r0 := w.inner.Transform()
	return r0
}

type wrappedStreamTransformerFactory struct {
	inner stream_transform.StreamTransformerFactory
}

func (w *wrappedStreamTransformerFactory) GetTransformer(input string) (StreamTransformer, error) {
	r0, r1 := w.inner.GetTransformer(input)
	return &wrappedStreamTransformer{inner: r0}, r1
}

func (w *wrappedStreamTransformerFactory) IsTransformable() bool {
	r0 := w.inner.IsTransformable()
	return r0
}

type wrappedMapReader struct {
	inner streaming.MapReader
}

func (w *wrappedMapReader) Read() ([]map[string]interface{}, error) {
	r0, r1 := w.inner.Read()
	return r0, r1
}

type wrappedMapStream struct {
	inner streaming.MapStream
}

func (w *wrappedMapStream) Write(p0 []map[string]interface{}) error {
	r0 := w.inner.Write(p0)
	return r0
}

type wrappedMapStreamCollection struct {
	inner streaming.MapStreamCollection
}

func (w *wrappedMapStreamCollection) Len() int {
	r0 := w.inner.Len()
	return r0
}

func (w *wrappedMapStreamCollection) Push(p0 *wrappedMapStream) {
	w.inner.Push(p0.inner)
	return
}

type wrappedAuthDTO struct {
	inner surface.AuthDTO
}

func (w *wrappedAuthDTO) GetAccountID() string {
	r0 := w.inner.GetAccountID()
	return r0
}

func (w *wrappedAuthDTO) GetAccountIDEnvVar() string {
	r0 := w.inner.GetAccountIDEnvVar()
	return r0
}

func (w *wrappedAuthDTO) GetAuthStyle() int {
	r0 := w.inner.GetAuthStyle()
	return r0
}

func (w *wrappedAuthDTO) GetClientID() string {
	r0 := w.inner.GetClientID()
	return r0
}

func (w *wrappedAuthDTO) GetClientIDEnvVar() string {
	r0 := w.inner.GetClientIDEnvVar()
	return r0
}

func (w *wrappedAuthDTO) GetClientSecret() string {
	r0 := w.inner.GetClientSecret()
	return r0
}

func (w *wrappedAuthDTO) GetClientSecretEnvVar() string {
	r0 := w.inner.GetClientSecretEnvVar()
	return r0
}

func (w *wrappedAuthDTO) GetEnvVarAPIKeyStr() string {
	r0 := w.inner.GetEnvVarAPIKeyStr()
	return r0
}

func (w *wrappedAuthDTO) GetEnvVarAPISecretStr() string {
	r0 := w.inner.GetEnvVarAPISecretStr()
	return r0
}

func (w *wrappedAuthDTO) GetEnvVarPassword() string {
	r0 := w.inner.GetEnvVarPassword()
	return r0
}

func (w *wrappedAuthDTO) GetEnvVarUsername() string {
	r0 := w.inner.GetEnvVarUsername()
	return r0
}

func (w *wrappedAuthDTO) GetGrantType() string {
	r0 := w.inner.GetGrantType()
	return r0
}

func (w *wrappedAuthDTO) GetInlineBasicCredentials() string {
	r0 := w.inner.GetInlineBasicCredentials()
	return r0
}

func (w *wrappedAuthDTO) GetKeyEnvVar() string {
	r0 := w.inner.GetKeyEnvVar()
	return r0
}

func (w *wrappedAuthDTO) GetKeyFilePath() string {
	r0 := w.inner.GetKeyFilePath()
	return r0
}

func (w *wrappedAuthDTO) GetKeyFilePathEnvVar() string {
	r0 := w.inner.GetKeyFilePathEnvVar()
	return r0
}

func (w *wrappedAuthDTO) GetKeyID() string {
	r0 := w.inner.GetKeyID()
	return r0
}

func (w *wrappedAuthDTO) GetKeyIDEnvVar() string {
	r0 := w.inner.GetKeyIDEnvVar()
	return r0
}

func (w *wrappedAuthDTO) GetLocation() string {
	r0 := w.inner.GetLocation()
	return r0
}

func (w *wrappedAuthDTO) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w *wrappedAuthDTO) GetScopes() []string {
	r0 := w.inner.GetScopes()
	return r0
}

func (w *wrappedAuthDTO) GetSubject() string {
	r0 := w.inner.GetSubject()
	return r0
}

func (w *wrappedAuthDTO) GetSuccessor() (AuthDTO, bool) {
	r0, r1 := w.inner.GetSuccessor()
	return &wrappedAuthDTO{inner: r0}, r1
}

func (w *wrappedAuthDTO) GetTokenURL() string {
	r0 := w.inner.GetTokenURL()
	return r0
}

func (w *wrappedAuthDTO) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

func (w *wrappedAuthDTO) GetValuePrefix() string {
	r0 := w.inner.GetValuePrefix()
	return r0
}

func (w *wrappedAuthDTO) GetValues() url.Values {
	r0 := w.inner.GetValues()
	return r0
}

type wrappedIDiscoveryAdapter struct {
	inner discovery.IDiscoveryAdapter
}

func (w *wrappedIDiscoveryAdapter) GetProvider(providerKey string) (Provider, error) {
	r0, r1 := w.inner.GetProvider(providerKey)
	return &wrappedProvider{inner: r0}, r1
}

func (w *wrappedIDiscoveryAdapter) GetResourcesMap(prov *wrappedProvider, serviceKey string) (map[string]Resource, error) {
	r0, r1 := w.inner.GetResourcesMap(prov.inner, serviceKey)
	return wrapMapString_Resource(r0), r1
}

func (w *wrappedIDiscoveryAdapter) GetServiceHandlesMap(prov *wrappedProvider) (map[string]ProviderService, error) {
	r0, r1 := w.inner.GetServiceHandlesMap(prov.inner)
	return wrapMapString_ProviderService(r0), r1
}

func (w *wrappedIDiscoveryAdapter) GetServiceShard(prov *wrappedProvider, serviceKey string, resourceKey string) (Service, error) {
	r0, r1 := w.inner.GetServiceShard(prov.inner, serviceKey, resourceKey)
	return &wrappedService{inner: r0}, r1
}

func (w *wrappedIDiscoveryAdapter) PersistStaticExternalSQLDataSource(prov *wrappedProvider) error {
	r0 := w.inner.PersistStaticExternalSQLDataSource(prov.inner)
	return r0
}

type wrappedAddressSpaceFormulator struct {
	inner radix_tree_address_space.AddressSpaceFormulator
}

func (w *wrappedAddressSpaceFormulator) Formulate() error {
	r0 := w.inner.Formulate()
	return r0
}

func (w *wrappedAddressSpaceFormulator) GetAddressSpace() AddressSpace {
	r0 := w.inner.GetAddressSpace()
	return &wrappedAddressSpace{inner: r0}
}

type wrappedSQLEngine struct {
	inner sqlengine.SQLEngine
}

func (w *wrappedSQLEngine) CacheStoreGet(p0 string) ([]byte, error) {
	r0, r1 := w.inner.CacheStoreGet(p0)
	return r0, r1
}

func (w *wrappedSQLEngine) CacheStorePut(p0 string, p1 []byte, p2 string, p3 int) error {
	r0 := w.inner.CacheStorePut(p0, p1, p2, p3)
	return r0
}

func (w *wrappedSQLEngine) Exec(p0 string, p1 ...interface{}) (sql.Result, error) {
	r0, r1 := w.inner.Exec(p0, p1)
	return r0, r1
}

func (w *wrappedSQLEngine) ExecInTxn(queries []string) error {
	r0 := w.inner.ExecInTxn(queries)
	return r0
}

func (w *wrappedSQLEngine) GetCurrentDiscoveryGenerationID(discoveryID string) (int, error) {
	r0, r1 := w.inner.GetCurrentDiscoveryGenerationID(discoveryID)
	return r0, r1
}

func (w *wrappedSQLEngine) GetCurrentGenerationID() (int, error) {
	r0, r1 := w.inner.GetCurrentGenerationID()
	return r0, r1
}

func (w *wrappedSQLEngine) GetDB() (*sql.DB, error) {
	r0, r1 := w.inner.GetDB()
	return r0, r1
}

func (w *wrappedSQLEngine) GetNextDiscoveryGenerationID(discoveryID string) (int, error) {
	r0, r1 := w.inner.GetNextDiscoveryGenerationID(discoveryID)
	return r0, r1
}

func (w *wrappedSQLEngine) GetNextGenerationID() (int, error) {
	r0, r1 := w.inner.GetNextGenerationID()
	return r0, r1
}

func (w *wrappedSQLEngine) GetNextSessionID(p0 int) (int, error) {
	r0, r1 := w.inner.GetNextSessionID(p0)
	return r0, r1
}

func (w *wrappedSQLEngine) GetTx() (*sql.Tx, error) {
	r0, r1 := w.inner.GetTx()
	return r0, r1
}

func (w *wrappedSQLEngine) Query(p0 string, p1 ...interface{}) (*sql.Rows, error) {
	r0, r1 := w.inner.Query(p0, p1)
	return r0, r1
}

func (w *wrappedSQLEngine) QueryRow(query string, args ...any) *sql.Row {
	r0 := w.inner.QueryRow(query, args)
	return r0
}

/*
type GraphQL interface {
	GetCursorJSONPath() (string, bool)
	GetQuery() string
	GetResponseJSONPath() (string, bool)
	unwrap() anysdk.GraphQL
}

*/

type wrappedMethodSet struct {
	inner anysdk.MethodSet
}

func (w *wrappedMethodSet) Size() int {
	r0 := len(w.inner)
	return r0
}

func (w *wrappedMethodSet) GetFirstMatch(params map[string]interface{}) (StandardOperationStore, map[string]interface{}, bool) {
	r0, r1, r2 := w.inner.GetFirstMatch(params)
	return &wrappedStandardOperationStore{inner: r0}, r1, r2
}

func (w *wrappedMethodSet) GetFirstNamespaceMatch(params map[string]any) (StandardOperationStore, map[string]any, bool) {
	r0, r1, r2 := w.inner.GetFirstNamespaceMatch(params)
	return &wrappedStandardOperationStore{inner: r0}, r1, r2
}

func (w *wrappedMethodSet) GetFirst() (StandardOperationStore, string, bool) {
	r0, r1, r2 := w.inner.GetFirst()
	return &wrappedStandardOperationStore{inner: r0}, r1, r2
}

type wrappedOpenAPIService struct {
	inner anysdk.OpenAPIService
}

func (w *wrappedOpenAPIService) unwrapOpenapi3Service() anysdk.OpenAPIService {
	return w.inner
}

func (w *wrappedOpenAPIService) unwrap() anysdk.Service {
	return w.inner
}

func (w *wrappedOpenAPIService) GetResource(resourceName string) (Resource, error) {
	r0, r1 := w.inner.GetResource(resourceName)
	return &wrappedResource{inner: r0}, r1
}

func (w *wrappedOpenAPIService) GetSchema(key string) (Schema, error) {
	r0, r1 := w.inner.GetSchema(key)
	return newWrappedSchemaFromAnySdkSchema(r0), r1
}

func (w *wrappedOpenAPIService) GetServers() (openapi3.Servers, bool) {
	r0, r1 := w.inner.GetServers()
	return r0, r1
}

/*
type ResourceRegister interface {
	//
	// GetServiceDocPath() *ServiceRef
	ObtainServiceDocUrl(resourceKey string) string
	SetProviderService(ps ProviderService)
	SetProvider(p Provider)
	GetResources() map[string]Resource
	GetResource(string) (Resource, bool)
	unwrap() anysdk.ResourceRegister
}
*/

type wrappedResourceRegister struct {
	inner anysdk.ResourceRegister
}

func (w *wrappedResourceRegister) ObtainServiceDocUrl(resourceKey string) string {
	r0 := w.inner.ObtainServiceDocUrl(resourceKey)
	return r0
}

func (w *wrappedResourceRegister) SetProviderService(ps ProviderService) {
	w.inner.SetProviderService(ps.unwrap())
	return
}

func (w *wrappedResourceRegister) SetProvider(p Provider) {
	w.inner.SetProvider(p.unwrap())
	return
}

func (w *wrappedResourceRegister) GetResources() map[string]Resource {
	r0 := w.inner.GetResources()
	return wrapMapString_Resource(r0)
}

func (w *wrappedResourceRegister) GetResource(resourceKey string) (Resource, bool) {
	r0, r1 := w.inner.GetResource(resourceKey)
	return &wrappedResource{inner: r0}, r1
}

func (w *wrappedResourceRegister) unwrap() anysdk.ResourceRegister {
	return w.inner
}

type wrappedDiscoveryAdapter struct {
	inner discovery.IDiscoveryAdapter
}

func (w *wrappedDiscoveryAdapter) unwrap() discovery.IDiscoveryAdapter {
	return w.inner
}

func (w *wrappedDiscoveryAdapter) GetProvider(providerKey string) (Provider, error) {
	r0, r1 := w.inner.GetProvider(providerKey)
	return &wrappedProvider{inner: r0}, r1
}

func (w *wrappedDiscoveryAdapter) GetResourcesMap(prov Provider, serviceKey string) (map[string]Resource, error) {
	r0, r1 := w.inner.GetResourcesMap(prov.unwrap(), serviceKey)
	return wrapMapString_Resource(r0), r1
}

func (w *wrappedDiscoveryAdapter) GetServiceHandlesMap(prov Provider) (map[string]ProviderService, error) {
	r0, r1 := w.inner.GetServiceHandlesMap(prov.unwrap())
	return wrapMapString_ProviderService(r0), r1
}

func (w *wrappedDiscoveryAdapter) GetServiceShard(prov Provider, serviceKey string, resourceKey string) (Service, error) {
	r0, r1 := w.inner.GetServiceShard(prov.unwrap(), serviceKey, resourceKey)
	return &wrappedService{inner: r0}, r1
}

func (w *wrappedDiscoveryAdapter) PersistStaticExternalSQLDataSource(prov Provider) error {
	r0 := w.inner.PersistStaticExternalSQLDataSource(prov.unwrap())
	return r0
}

var (
	_ anysdk.HTTPArmoury = &reverseWrappedHTTPArmoury{}
)

/*

type HTTPArmoury interface {
	AddRequestParams(HTTPArmouryParameters)
	GetRequestParams() []HTTPArmouryParameters
	GetRequestSchema() Schema
	GetResponseSchema() Schema
	SetRequestParams([]HTTPArmouryParameters)
	SetRequestSchema(Schema)
	SetResponseSchema(Schema)
}

*/

type reverseWrappedHTTPArmoury struct {
	inner HTTPArmoury
}

func (w *reverseWrappedHTTPArmoury) AddRequestParams(params anysdk.HTTPArmouryParameters) {
	w.inner.AddRequestParams(params)
	return
}

func (w *reverseWrappedHTTPArmoury) GetRequestParams() []anysdk.HTTPArmouryParameters {
	r0 := w.inner.GetRequestParams()
	rv := make([]anysdk.HTTPArmouryParameters, len(r0))
	for i, p := range r0 {
		rv[i] = &wrappedHTTPArmouryParameters{inner: p}
	}
	return rv
}

var (
	_ persistence.PersistenceSystem = &reverseWrappedPersistenceSystem{}
)

type reverseWrappedPersistenceSystem struct {
	inner PersistenceSystem
}

func (w *reverseWrappedPersistenceSystem) GetSystemName() string {
	return w.inner.GetSystemName()
}

func (w *reverseWrappedPersistenceSystem) HandleExternalTables(providerName string, externalTables map[string]anysdk.SQLExternalTable) error {
	internalTables := make(map[string]SQLExternalTable, len(externalTables))
	for k, v := range externalTables {
		internalTables[k] = &wrappedSQLExternalTable{inner: v}
	}
	return w.inner.HandleExternalTables(providerName, internalTables)
}

func (w *reverseWrappedPersistenceSystem) HandleViewCollection(views []anysdk.View) error {
	localViews := make([]View, len(views))
	for i, v := range views {
		localViews[i] = &wrappedView{inner: v}
	}
	return w.inner.HandleViewCollection(localViews)
}

func (w *reverseWrappedPersistenceSystem) CacheStoreGet(key string) ([]byte, error) {
	return w.inner.CacheStoreGet(key)
}

func (w *reverseWrappedPersistenceSystem) CacheStorePut(key string, value []byte, expiration string, ttl int) error {
	return w.inner.CacheStorePut(key, value, expiration, ttl)
}

type wrappedColumnDescriptor struct {
	inner anysdk.ColumnDescriptor
}

func (w *wrappedColumnDescriptor) unwrap() anysdk.ColumnDescriptor {
	return w.inner
}

func (w *wrappedColumnDescriptor) GetVal() *sqlparser.SQLVal {
	return w.inner.GetVal()
}

func (w *wrappedColumnDescriptor) GetNode() sqlparser.SQLNode {
	return w.inner.GetNode()
}

func (w *wrappedColumnDescriptor) GetDecoratedCol() string {
	return w.inner.GetDecoratedCol()
}

func (w *wrappedColumnDescriptor) GetQualifier() string {
	return w.inner.GetQualifier()
}

func (w *wrappedColumnDescriptor) GetRepresentativeSchema() Schema {
	return newWrappedSchemaFromAnySdkSchema(w.inner.GetRepresentativeSchema())
}

func (w *wrappedColumnDescriptor) GetSchema() Schema {
	return newWrappedSchemaFromAnySdkSchema(w.inner.GetSchema())
}

func (w *wrappedColumnDescriptor) GetAlias() string {
	return w.inner.GetAlias()
}

func (w *wrappedColumnDescriptor) GetName() string {
	return w.inner.GetName()
}

func (w *wrappedColumnDescriptor) GetIdentifier() string {
	return w.inner.GetIdentifier()
}

func newColDescriptorFromAnySdkColumnDescriptor(c anysdk.ColumnDescriptor) ColumnDescriptor {
	return &wrappedColumnDescriptor{inner: c}
}

type wrappedHTTPPreparatorConfig struct {
	inner anysdk.HTTPPreparatorConfig
}

func (w *wrappedHTTPPreparatorConfig) IsFromAnnotation() bool {
	r0 := w.inner.IsFromAnnotation()
	return r0
}

func (w *wrappedHTTPPreparatorConfig) unwrap() anysdk.HTTPPreparatorConfig {
	return w.inner
}

type wrappedTTLDiscoveryStore struct {
	inner discovery.IDiscoveryStore
}

func (w *wrappedTTLDiscoveryStore) ProcessProviderDiscoveryDoc(apiDiscoveryDocURL string, alias string) (Provider, error) {
	prov, err := w.inner.ProcessProviderDiscoveryDoc(apiDiscoveryDocURL, alias)
	if err != nil {
		return nil, err
	}
	return &wrappedProvider{inner: prov}, nil
}

func (w *wrappedTTLDiscoveryStore) PersistServiceShard(prov Provider, sh ProviderService, resourceKey string) (Service, error) {
	service, err := w.inner.PersistServiceShard(prov.unwrap(), sh.unwrap(), resourceKey)
	if err != nil {
		return nil, err
	}
	return &wrappedService{inner: service}, nil
}

func (w *wrappedTTLDiscoveryStore) unwrap() discovery.IDiscoveryStore {
	return w.inner
}
