// Code generated by tools/surfacegen (wrappers) - DO NOT EDIT.
package formulation

import (
	"bytes"
	"context"
	"crypto/tls"
	"database/sql"
	"io"
	"net/http"
	"net/url"
	"regexp"
	"text/template"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/lib/pq/oid"
	"github.com/stackql/any-sdk/anysdk"
	"github.com/stackql/any-sdk/pkg/auth_util"
	"github.com/stackql/any-sdk/pkg/client"
	"github.com/stackql/any-sdk/pkg/constants"
	"github.com/stackql/any-sdk/pkg/db/sqlcontrol"
	"github.com/stackql/any-sdk/pkg/dto"
	"github.com/stackql/any-sdk/pkg/graphql"
	"github.com/stackql/any-sdk/pkg/httpelement"
	"github.com/stackql/any-sdk/pkg/internaldto"
	"github.com/stackql/any-sdk/pkg/local_template_executor"
	"github.com/stackql/any-sdk/pkg/name_mangle"
	"github.com/stackql/any-sdk/pkg/netutils"
	"github.com/stackql/any-sdk/pkg/providerinvoker"
	"github.com/stackql/any-sdk/pkg/response"
	"github.com/stackql/any-sdk/pkg/stream_transform"
	"github.com/stackql/any-sdk/pkg/streaming"
	"github.com/stackql/any-sdk/pkg/surface"
	"github.com/stackql/any-sdk/public/discovery"
	"github.com/stackql/any-sdk/public/radix_tree_address_space"
	"github.com/stackql/any-sdk/public/sqlengine"
	"github.com/stackql/stackql-parser/go/sqltypes"
)

func wrapMapString_Addressable(in map[string]anysdk.Addressable) map[string]Addressable {
	if in == nil {
		return nil
	}
	out := make(map[string]Addressable, len(in))
	for k, v := range in {
		out[k] = Addressable{inner: v}
	}
	return out
}

func unwrapMapString_Addressable(in map[string]Addressable) map[string]anysdk.Addressable {
	if in == nil {
		return nil
	}
	out := make(map[string]anysdk.Addressable, len(in))
	for k, v := range in {
		out[k] = v.inner
	}
	return out
}

func wrapMapString_ProviderDescription(in map[string]anysdk.ProviderDescription) map[string]ProviderDescription {
	if in == nil {
		return nil
	}
	out := make(map[string]ProviderDescription, len(in))
	for k, v := range in {
		out[k] = ProviderDescription{inner: v}
	}
	return out
}

func unwrapMapString_ProviderDescription(in map[string]ProviderDescription) map[string]anysdk.ProviderDescription {
	if in == nil {
		return nil
	}
	out := make(map[string]anysdk.ProviderDescription, len(in))
	for k, v := range in {
		out[k] = v.inner
	}
	return out
}

func wrapMapString_ProviderService(in map[string]anysdk.ProviderService) map[string]ProviderService {
	if in == nil {
		return nil
	}
	out := make(map[string]ProviderService, len(in))
	for k, v := range in {
		out[k] = ProviderService{inner: v}
	}
	return out
}

func unwrapMapString_ProviderService(in map[string]ProviderService) map[string]anysdk.ProviderService {
	if in == nil {
		return nil
	}
	out := make(map[string]anysdk.ProviderService, len(in))
	for k, v := range in {
		out[k] = v.inner
	}
	return out
}

func wrapMapString_Resource(in map[string]anysdk.Resource) map[string]Resource {
	if in == nil {
		return nil
	}
	out := make(map[string]Resource, len(in))
	for k, v := range in {
		out[k] = Resource{inner: v}
	}
	return out
}

func unwrapMapString_Resource(in map[string]Resource) map[string]anysdk.Resource {
	if in == nil {
		return nil
	}
	out := make(map[string]anysdk.Resource, len(in))
	for k, v := range in {
		out[k] = v.inner
	}
	return out
}

func wrapPtr_AuthCtx(in *dto.AuthCtx) *AuthCtx {
	if in == nil {
		return nil
	}
	return &AuthCtx{inner: in}
}

func wrapSlice_Column(in []anysdk.Column) []Column {
	if in == nil {
		return nil
	}
	out := make([]Column, 0, len(in))
	for _, v := range in {
		out = append(out, Column{inner: v})
	}
	return out
}

func unwrapSlice_Column(in []Column) []anysdk.Column {
	if in == nil {
		return nil
	}
	out := make([]anysdk.Column, 0, len(in))
	for _, v := range in {
		out = append(out, v.inner)
	}
	return out
}

func wrapSlice_HTTPArmouryParameters(in []anysdk.HTTPArmouryParameters) []HTTPArmouryParameters {
	if in == nil {
		return nil
	}
	out := make([]HTTPArmouryParameters, 0, len(in))
	for _, v := range in {
		out = append(out, HTTPArmouryParameters{inner: v})
	}
	return out
}

func unwrapSlice_HTTPArmouryParameters(in []HTTPArmouryParameters) []anysdk.HTTPArmouryParameters {
	if in == nil {
		return nil
	}
	out := make([]anysdk.HTTPArmouryParameters, 0, len(in))
	for _, v := range in {
		out = append(out, v.inner)
	}
	return out
}

func wrapSlice_SQLExternalColumn(in []anysdk.SQLExternalColumn) []SQLExternalColumn {
	if in == nil {
		return nil
	}
	out := make([]SQLExternalColumn, 0, len(in))
	for _, v := range in {
		out = append(out, SQLExternalColumn{inner: v})
	}
	return out
}

func unwrapSlice_SQLExternalColumn(in []SQLExternalColumn) []anysdk.SQLExternalColumn {
	if in == nil {
		return nil
	}
	out := make([]anysdk.SQLExternalColumn, 0, len(in))
	for _, v := range in {
		out = append(out, v.inner)
	}
	return out
}

func wrapSlice_StandardOperationStore(in []anysdk.StandardOperationStore) []StandardOperationStore {
	if in == nil {
		return nil
	}
	out := make([]StandardOperationStore, 0, len(in))
	for _, v := range in {
		out = append(out, StandardOperationStore{inner: v})
	}
	return out
}

func unwrapSlice_StandardOperationStore(in []StandardOperationStore) []anysdk.StandardOperationStore {
	if in == nil {
		return nil
	}
	out := make([]anysdk.StandardOperationStore, 0, len(in))
	for _, v := range in {
		out = append(out, v.inner)
	}
	return out
}

func wrapSlice_View(in []anysdk.View) []View {
	if in == nil {
		return nil
	}
	out := make([]View, 0, len(in))
	for _, v := range in {
		out = append(out, View{inner: v})
	}
	return out
}

func unwrapSlice_View(in []View) []anysdk.View {
	if in == nil {
		return nil
	}
	out := make([]anysdk.View, 0, len(in))
	for _, v := range in {
		out = append(out, v.inner)
	}
	return out
}

type AuthMetadata struct {
	inner *anysdk.AuthMetadata
}

func (w *AuthMetadata) GetHeaders() []string {
	r0 := w.inner.GetHeaders()
	return r0
}

func (w *AuthMetadata) ToMap() map[string]interface{} {
	r0 := w.inner.ToMap()
	return r0
}

type AuthCtx struct {
	inner *dto.AuthCtx
}

func (w *AuthCtx) Clone() *AuthCtx {
	r0 := w.inner.Clone()
	return wrapPtr_AuthCtx(r0)
}

func (w *AuthCtx) GetCredentialsBytes() ([]byte, error) {
	r0, r1 := w.inner.GetCredentialsBytes()
	return r0, r1
}

func (w *AuthCtx) GetCredentialsSourceDescriptorString() string {
	r0 := w.inner.GetCredentialsSourceDescriptorString()
	return r0
}

func (w *AuthCtx) GetSQLCfg() (SQLBackendCfg, bool) {
	r0, r1 := w.inner.GetSQLCfg()
	return SQLBackendCfg{inner: r0}, r1
}

func (w *AuthCtx) HasKey() bool {
	r0 := w.inner.HasKey()
	return r0
}

type RuntimeCtx struct {
	inner dto.RuntimeCtx
}

func (w RuntimeCtx) Copy() RuntimeCtx {
	r0 := w.inner.Copy()
	return RuntimeCtx{inner: r0}
}

type AddressSpace struct {
	inner anysdk.AddressSpace
}

func (w AddressSpace) ToRelation(p0 anysdk.AddressSpaceExpansionConfig) (Relation, error) {
	r0, r1 := w.inner.ToRelation(p0)
	return Relation{inner: r0}, r1
}

func DeprecatedNewAddressable(inner anysdk.Addressable) Addressable {
	return Addressable{inner: inner}
}

type Addressable struct {
	inner anysdk.Addressable
}

func (w Addressable) ConditionIsValid(lhs string, rhs interface{}) bool {
	r0 := w.inner.ConditionIsValid(lhs, rhs)
	return r0
}

func (w Addressable) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w Addressable) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

type Column struct {
	inner anysdk.Column
}

func (w Column) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w Column) GetSchema() Schema {
	r0 := w.inner.GetSchema()
	return Schema{inner: r0}
}

func (w Column) GetWidth() int {
	r0 := w.inner.GetWidth()
	return r0
}

type ExpectedRequest struct {
	inner anysdk.ExpectedRequest
}

func (w ExpectedRequest) GetBodyMediaType() string {
	r0 := w.inner.GetBodyMediaType()
	return r0
}

type ExpectedResponse struct {
	inner anysdk.ExpectedResponse
}

func (w ExpectedResponse) GetObjectKey() string {
	r0 := w.inner.GetObjectKey()
	return r0
}

func (w ExpectedResponse) GetTransform() (Transform, bool) {
	r0, r1 := w.inner.GetTransform()
	return Transform{inner: r0}, r1
}

type GraphQL struct {
	inner anysdk.GraphQL
}

func (w GraphQL) GetCursorJSONPath() (string, bool) {
	r0, r1 := w.inner.GetCursorJSONPath()
	return r0, r1
}

func (w GraphQL) GetQuery() string {
	r0 := w.inner.GetQuery()
	return r0
}

func (w GraphQL) GetResponseJSONPath() (string, bool) {
	r0, r1 := w.inner.GetResponseJSONPath()
	return r0, r1
}

type HTTPArmoury struct {
	inner anysdk.HTTPArmoury
}

func (w HTTPArmoury) GetRequestParams() []HTTPArmouryParameters {
	r0 := w.inner.GetRequestParams()
	return wrapSlice_HTTPArmouryParameters(r0)
}

func (w HTTPArmoury) SetRequestParams(p0 []HTTPArmouryParameters) {
	inner_p0 := unwrapSlice_HTTPArmouryParameters(p0)
	w.inner.SetRequestParams(inner_p0)
	return
}

type HTTPArmouryParameters struct {
	inner anysdk.HTTPArmouryParameters
}

func (w HTTPArmouryParameters) Encode() string {
	r0 := w.inner.Encode()
	return r0
}

func (w HTTPArmouryParameters) GetArgList() client.AnySdkArgList {
	r0 := w.inner.GetArgList()
	return r0
}

func (w HTTPArmouryParameters) GetParameters() HttpParameters {
	r0 := w.inner.GetParameters()
	return HttpParameters{inner: r0}
}

func (w HTTPArmouryParameters) GetQuery() url.Values {
	r0 := w.inner.GetQuery()
	return r0
}

func (w HTTPArmouryParameters) GetRequest() *http.Request {
	r0 := w.inner.GetRequest()
	return r0
}

func (w HTTPArmouryParameters) SetNextPage(ops OperationStore, token string, tokenKey HTTPElement) (*http.Request, error) {
	r0, r1 := w.inner.SetNextPage(ops.inner, token, tokenKey.inner)
	return r0, r1
}

func (w HTTPArmouryParameters) SetRawQuery(p0 string) {
	w.inner.SetRawQuery(p0)
	return
}

func (w HTTPArmouryParameters) ToFlatMap() (map[string]interface{}, error) {
	r0, r1 := w.inner.ToFlatMap()
	return r0, r1
}

type HTTPPreparator struct {
	inner anysdk.HTTPPreparator
}

func (w HTTPPreparator) BuildHTTPRequestCtx(p0 anysdk.HTTPPreparatorConfig) (HTTPArmoury, error) {
	r0, r1 := w.inner.BuildHTTPRequestCtx(p0)
	return HTTPArmoury{inner: r0}, r1
}

type HttpParameters struct {
	inner anysdk.HttpParameters
}

func (w HttpParameters) GetInlineParameterFlatMap() (map[string]interface{}, error) {
	r0, r1 := w.inner.GetInlineParameterFlatMap()
	return r0, r1
}

func (w HttpParameters) ToFlatMap() (map[string]interface{}, error) {
	r0, r1 := w.inner.ToFlatMap()
	return r0, r1
}

type HttpPreparatorStream struct {
	inner anysdk.HttpPreparatorStream
}

func (w HttpPreparatorStream) Next() (HTTPPreparator, bool) {
	r0, r1 := w.inner.Next()
	return HTTPPreparator{inner: r0}, r1
}

func (w HttpPreparatorStream) Write(p0 HTTPPreparator) error {
	r0 := w.inner.Write(p0.inner)
	return r0
}

type ITable struct {
	inner anysdk.ITable
}

func (w ITable) GetKey(p0 string) (interface{}, error) {
	r0, r1 := w.inner.GetKey(p0)
	return r0, r1
}

func (w ITable) GetKeyAsSqlVal(p0 string) (sqltypes.Value, error) {
	r0, r1 := w.inner.GetKeyAsSqlVal(p0)
	return r0, r1
}

func (w ITable) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w ITable) KeyExists(p0 string) bool {
	r0 := w.inner.KeyExists(p0)
	return r0
}

type MethodAnalysisOutput struct {
	inner anysdk.MethodAnalysisOutput
}

func (w MethodAnalysisOutput) GetInsertTabulation() Tabulation {
	r0 := w.inner.GetInsertTabulation()
	return Tabulation{inner: r0}
}

func (w MethodAnalysisOutput) GetItemSchema() (Schema, bool) {
	r0, r1 := w.inner.GetItemSchema()
	return Schema{inner: r0}, r1
}

func (w MethodAnalysisOutput) GetOrderedStarColumnsNames() ([]string, error) {
	r0, r1 := w.inner.GetOrderedStarColumnsNames()
	return r0, r1
}

func (w MethodAnalysisOutput) GetSelectTabulation() Tabulation {
	r0 := w.inner.GetSelectTabulation()
	return Tabulation{inner: r0}
}

func (w MethodAnalysisOutput) IsAwait() bool {
	r0 := w.inner.IsAwait()
	return r0
}

func (w MethodAnalysisOutput) IsNilResponseAllowed() bool {
	r0 := w.inner.IsNilResponseAllowed()
	return r0
}

type MethodAnalyzer struct {
	inner anysdk.MethodAnalyzer
}

func (w MethodAnalyzer) AnalyzeUnaryAction(p0 anysdk.MethodAnalysisInput) (MethodAnalysisOutput, error) {
	r0, r1 := w.inner.AnalyzeUnaryAction(p0)
	return MethodAnalysisOutput{inner: r0}, r1
}

type Methods struct {
	inner anysdk.Methods
}

func (w Methods) OrderMethods() ([]StandardOperationStore, error) {
	r0, r1 := w.inner.OrderMethods()
	return wrapSlice_StandardOperationStore(r0), r1
}

type OperationInverse struct {
	inner anysdk.OperationInverse
}

func (w OperationInverse) GetOperationStore() (StandardOperationStore, bool) {
	r0, r1 := w.inner.GetOperationStore()
	return StandardOperationStore{inner: r0}, r1
}

type OperationStore struct {
	inner anysdk.OperationStore
}

func (w OperationStore) DeprecatedProcessResponse(response *http.Response) (map[string]interface{}, error) {
	r0, r1 := w.inner.DeprecatedProcessResponse(response)
	return r0, r1
}

func (w OperationStore) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w OperationStore) GetNonBodyParameters() map[string]Addressable {
	r0 := w.inner.GetNonBodyParameters()
	return wrapMapString_Addressable(r0)
}

func (w OperationStore) GetPaginationRequestTokenSemantic() (TokenSemantic, bool) {
	r0, r1 := w.inner.GetPaginationRequestTokenSemantic()
	return TokenSemantic{inner: r0}, r1
}

func (w OperationStore) GetPaginationResponseTokenSemantic() (TokenSemantic, bool) {
	r0, r1 := w.inner.GetPaginationResponseTokenSemantic()
	return TokenSemantic{inner: r0}, r1
}

func (w OperationStore) GetParameter(paramKey string) (Addressable, bool) {
	r0, r1 := w.inner.GetParameter(paramKey)
	return Addressable{inner: r0}, r1
}

func (w OperationStore) GetRequestBodySchema() (Schema, error) {
	r0, r1 := w.inner.GetRequestBodySchema()
	return Schema{inner: r0}, r1
}

func (w OperationStore) GetRequiredNonBodyParameters() map[string]Addressable {
	r0 := w.inner.GetRequiredNonBodyParameters()
	return wrapMapString_Addressable(r0)
}

func (w OperationStore) GetRequiredParameters() map[string]Addressable {
	r0 := w.inner.GetRequiredParameters()
	return wrapMapString_Addressable(r0)
}

func (w OperationStore) GetResource() Resource {
	r0 := w.inner.GetResource()
	return Resource{inner: r0}
}

func (w OperationStore) GetResponseBodySchemaAndMediaType() (Schema, string, error) {
	r0, r1, r2 := w.inner.GetResponseBodySchemaAndMediaType()
	return Schema{inner: r0}, r1, r2
}

func (w OperationStore) GetSelectItemsKey() string {
	r0 := w.inner.GetSelectItemsKey()
	return r0
}

func (w OperationStore) GetService() anysdk.OpenAPIService {
	r0 := w.inner.GetService()
	return r0
}

func (w OperationStore) IsRequestBodyAttributeRenamed(p0 string) bool {
	r0 := w.inner.IsRequestBodyAttributeRenamed(p0)
	return r0
}

func (w OperationStore) IsRequiredRequestBodyProperty(key string) bool {
	r0 := w.inner.IsRequiredRequestBodyProperty(key)
	return r0
}

func (w OperationStore) ProcessResponse(p0 *http.Response) (ProcessedOperationResponse, error) {
	r0, r1 := w.inner.ProcessResponse(p0)
	return ProcessedOperationResponse{inner: r0}, r1
}

func (w OperationStore) RenameRequestBodyAttribute(p0 string) (string, error) {
	r0, r1 := w.inner.RenameRequestBodyAttribute(p0)
	return r0, r1
}

func (w OperationStore) RevertRequestBodyAttributeRename(p0 string) (string, error) {
	r0, r1 := w.inner.RevertRequestBodyAttributeRename(p0)
	return r0, r1
}

type ProcessedOperationResponse struct {
	inner anysdk.ProcessedOperationResponse
}

func (w ProcessedOperationResponse) GetResponse() (Response, bool) {
	r0, r1 := w.inner.GetResponse()
	return Response{inner: r0}, r1
}

func (w ProcessedOperationResponse) GetReversal() (HTTPPreparator, bool) {
	r0, r1 := w.inner.GetReversal()
	return HTTPPreparator{inner: r0}, r1
}

type Provider struct {
	inner anysdk.Provider
}

func (w Provider) GetAuth() (AuthDTO, bool) {
	r0, r1 := w.inner.GetAuth()
	return AuthDTO{inner: r0}, r1
}

func (w Provider) GetDeleteItemsKey() string {
	r0 := w.inner.GetDeleteItemsKey()
	return r0
}

func (w Provider) GetMinStackQLVersion() string {
	r0 := w.inner.GetMinStackQLVersion()
	return r0
}

func (w Provider) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w Provider) GetProtocolType() (client.ClientProtocolType, error) {
	r0, r1 := w.inner.GetProtocolType()
	return r0, r1
}

type ProviderDescription struct {
	inner anysdk.ProviderDescription
}

func (w ProviderDescription) GetLatestVersion() (string, error) {
	r0, r1 := w.inner.GetLatestVersion()
	return r0, r1
}

type ProviderService struct {
	inner anysdk.ProviderService
}

func (w ProviderService) GetDescription() string {
	r0 := w.inner.GetDescription()
	return r0
}

func (w ProviderService) GetID() string {
	r0 := w.inner.GetID()
	return r0
}

func (w ProviderService) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w ProviderService) GetTitle() string {
	r0 := w.inner.GetTitle()
	return r0
}

func (w ProviderService) GetVersion() string {
	r0 := w.inner.GetVersion()
	return r0
}

func (w ProviderService) IsPreferred() bool {
	r0 := w.inner.IsPreferred()
	return r0
}

type RegistryAPI struct {
	inner anysdk.RegistryAPI
}

func (w RegistryAPI) ClearProviderCache(p0 string) error {
	r0 := w.inner.ClearProviderCache(p0)
	return r0
}

func (w RegistryAPI) GetLatestPublishedVersion(p0 string) (string, error) {
	r0, r1 := w.inner.GetLatestPublishedVersion(p0)
	return r0, r1
}

func (w RegistryAPI) ListAllAvailableProviders() (map[string]ProviderDescription, error) {
	r0, r1 := w.inner.ListAllAvailableProviders()
	return wrapMapString_ProviderDescription(r0), r1
}

func (w RegistryAPI) ListAllProviderVersions(p0 string) (map[string]ProviderDescription, error) {
	r0, r1 := w.inner.ListAllProviderVersions(p0)
	return wrapMapString_ProviderDescription(r0), r1
}

func (w RegistryAPI) ListLocallyAvailableProviders() map[string]ProviderDescription {
	r0 := w.inner.ListLocallyAvailableProviders()
	return wrapMapString_ProviderDescription(r0)
}

func (w RegistryAPI) LoadProviderByName(p0 string, p1 string) (Provider, error) {
	r0, r1 := w.inner.LoadProviderByName(p0, p1)
	return Provider{inner: r0}, r1
}

func (w RegistryAPI) PullAndPersistProviderArchive(p0 string, p1 string) error {
	r0 := w.inner.PullAndPersistProviderArchive(p0, p1)
	return r0
}

func (w RegistryAPI) RemoveProviderVersion(p0 string, p1 string) error {
	r0 := w.inner.RemoveProviderVersion(p0, p1)
	return r0
}

type Relation struct {
	inner anysdk.Relation
}

func (w Relation) GetColumnDescriptors() []anysdk.ColumnDescriptor {
	r0 := w.inner.GetColumnDescriptors()
	return r0
}

func (w Relation) GetColumns() []Column {
	r0 := w.inner.GetColumns()
	return wrapSlice_Column(r0)
}

type Resource struct {
	inner anysdk.Resource
}

func (w Resource) FindMethod(key string) (StandardOperationStore, error) {
	r0, r1 := w.inner.FindMethod(key)
	return StandardOperationStore{inner: r0}, r1
}

func (w Resource) GetFirstMethodFromSQLVerb(sqlVerb string) (StandardOperationStore, string, bool) {
	r0, r1, r2 := w.inner.GetFirstMethodFromSQLVerb(sqlVerb)
	return StandardOperationStore{inner: r0}, r1, r2
}

func (w Resource) GetFirstNamespaceMethodMatchFromSQLVerb(sqlVerb string, parameters map[string]interface{}) (StandardOperationStore, map[string]interface{}, bool) {
	r0, r1, r2 := w.inner.GetFirstNamespaceMethodMatchFromSQLVerb(sqlVerb, parameters)
	return StandardOperationStore{inner: r0}, r1, r2
}

func (w Resource) GetID() string {
	r0 := w.inner.GetID()
	return r0
}

func (w Resource) GetMethodsMatched() Methods {
	r0 := w.inner.GetMethodsMatched()
	return Methods{inner: r0}
}

func (w Resource) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w Resource) GetViewsForSqlDialect(sqlDialect string) ([]View, bool) {
	r0, r1 := w.inner.GetViewsForSqlDialect(sqlDialect)
	return wrapSlice_View(r0), r1
}

func (w Resource) ToMap(extended bool) map[string]interface{} {
	r0 := w.inner.ToMap(extended)
	return r0
}

type SQLExternalColumn struct {
	inner anysdk.SQLExternalColumn
}

func (w SQLExternalColumn) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w SQLExternalColumn) GetOid() uint32 {
	r0 := w.inner.GetOid()
	return r0
}

func (w SQLExternalColumn) GetPrecision() int {
	r0 := w.inner.GetPrecision()
	return r0
}

func (w SQLExternalColumn) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

func (w SQLExternalColumn) GetWidth() int {
	r0 := w.inner.GetWidth()
	return r0
}

type SQLExternalTable struct {
	inner anysdk.SQLExternalTable
}

func (w SQLExternalTable) GetCatalogName() string {
	r0 := w.inner.GetCatalogName()
	return r0
}

func (w SQLExternalTable) GetColumns() []SQLExternalColumn {
	r0 := w.inner.GetColumns()
	return wrapSlice_SQLExternalColumn(r0)
}

func (w SQLExternalTable) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w SQLExternalTable) GetSchemaName() string {
	r0 := w.inner.GetSchemaName()
	return r0
}

type Schema struct {
	inner anysdk.Schema
}

func (w Schema) FindByPath(path string, visited map[string]bool) Schema {
	r0 := w.inner.FindByPath(path, visited)
	return Schema{inner: r0}
}

func (w Schema) GetAdditionalProperties() (Schema, bool) {
	r0, r1 := w.inner.GetAdditionalProperties()
	return Schema{inner: r0}, r1
}

func (w Schema) GetAllColumns(p0 string) []string {
	r0 := w.inner.GetAllColumns(p0)
	return r0
}

func (w Schema) GetItemsSchema() (Schema, error) {
	r0, r1 := w.inner.GetItemsSchema()
	return Schema{inner: r0}, r1
}

func (w Schema) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w Schema) GetProperties() (anysdk.Schemas, error) {
	r0, r1 := w.inner.GetProperties()
	return r0, r1
}

func (w Schema) GetProperty(propertyKey string) (Schema, bool) {
	r0, r1 := w.inner.GetProperty(propertyKey)
	return Schema{inner: r0}, r1
}

func (w Schema) GetPropertySchema(key string) (Schema, error) {
	r0, r1 := w.inner.GetPropertySchema(key)
	return Schema{inner: r0}, r1
}

func (w Schema) GetSelectSchema(itemsKey string, mediaType string) (Schema, string, error) {
	r0, r1, r2 := w.inner.GetSelectSchema(itemsKey, mediaType)
	return Schema{inner: r0}, r1, r2
}

func (w Schema) GetSelectionName() string {
	r0 := w.inner.GetSelectionName()
	return r0
}

func (w Schema) GetTitle() string {
	r0 := w.inner.GetTitle()
	return r0
}

func (w Schema) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

func (w Schema) IsBoolean() bool {
	r0 := w.inner.IsBoolean()
	return r0
}

func (w Schema) IsFloat() bool {
	r0 := w.inner.IsFloat()
	return r0
}

func (w Schema) IsIntegral() bool {
	r0 := w.inner.IsIntegral()
	return r0
}

func (w Schema) IsReadOnly() bool {
	r0 := w.inner.IsReadOnly()
	return r0
}

func (w Schema) IsRequired(key string) bool {
	r0 := w.inner.IsRequired(key)
	return r0
}

func (w Schema) SetKey(p0 string) {
	w.inner.SetKey(p0)
	return
}

func (w Schema) Tabulate(p0 bool, p1 string) Tabulation {
	r0 := w.inner.Tabulate(p0, p1)
	return Tabulation{inner: r0}
}

func (w Schema) ToDescriptionMap(extended bool) map[string]interface{} {
	r0 := w.inner.ToDescriptionMap(extended)
	return r0
}

type Service struct {
	inner anysdk.Service
}

func (w Service) GetResource(resourceName string) (Resource, error) {
	r0, r1 := w.inner.GetResource(resourceName)
	return Resource{inner: r0}, r1
}

func (w Service) GetSchema(key string) (Schema, error) {
	r0, r1 := w.inner.GetSchema(key)
	return Schema{inner: r0}, r1
}

func (w Service) GetServers() (openapi3.Servers, bool) {
	r0, r1 := w.inner.GetServers()
	return r0, r1
}

type StandardOperationStore struct {
	inner anysdk.StandardOperationStore
}

func (w StandardOperationStore) GetAddressSpace() (AddressSpace, bool) {
	r0, r1 := w.inner.GetAddressSpace()
	return AddressSpace{inner: r0}, r1
}

func (w StandardOperationStore) GetColumnOrder(extended bool) []string {
	r0 := w.inner.GetColumnOrder(extended)
	return r0
}

func (w StandardOperationStore) GetGraphQL() GraphQL {
	r0 := w.inner.GetGraphQL()
	return GraphQL{inner: r0}
}

func (w StandardOperationStore) GetInline() []string {
	r0 := w.inner.GetInline()
	return r0
}

func (w StandardOperationStore) GetInverse() (OperationInverse, bool) {
	r0, r1 := w.inner.GetInverse()
	return OperationInverse{inner: r0}, r1
}

func (w StandardOperationStore) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w StandardOperationStore) GetOptionalParameters() map[string]Addressable {
	r0 := w.inner.GetOptionalParameters()
	return wrapMapString_Addressable(r0)
}

func (w StandardOperationStore) GetPaginationRequestTokenSemantic() (TokenSemantic, bool) {
	r0, r1 := w.inner.GetPaginationRequestTokenSemantic()
	return TokenSemantic{inner: r0}, r1
}

func (w StandardOperationStore) GetPaginationResponseTokenSemantic() (TokenSemantic, bool) {
	r0, r1 := w.inner.GetPaginationResponseTokenSemantic()
	return TokenSemantic{inner: r0}, r1
}

func (w StandardOperationStore) GetParameter(paramKey string) (Addressable, bool) {
	r0, r1 := w.inner.GetParameter(paramKey)
	return Addressable{inner: r0}, r1
}

func (w StandardOperationStore) GetProjections() map[string]string {
	r0 := w.inner.GetProjections()
	return r0
}

func (w StandardOperationStore) GetRequest() (ExpectedRequest, bool) {
	r0, r1 := w.inner.GetRequest()
	return ExpectedRequest{inner: r0}, r1
}

func (w StandardOperationStore) GetRequestBodySchema() (Schema, error) {
	r0, r1 := w.inner.GetRequestBodySchema()
	return Schema{inner: r0}, r1
}

func (w StandardOperationStore) GetRequiredParameters() map[string]Addressable {
	r0 := w.inner.GetRequiredParameters()
	return wrapMapString_Addressable(r0)
}

func (w StandardOperationStore) GetResponse() (ExpectedResponse, bool) {
	r0, r1 := w.inner.GetResponse()
	return ExpectedResponse{inner: r0}, r1
}

func (w StandardOperationStore) GetResponseBodySchemaAndMediaType() (Schema, string, error) {
	r0, r1, r2 := w.inner.GetResponseBodySchemaAndMediaType()
	return Schema{inner: r0}, r1, r2
}

func (w StandardOperationStore) GetSelectItemsKey() string {
	r0 := w.inner.GetSelectItemsKey()
	return r0
}

func (w StandardOperationStore) GetSelectSchemaAndObjectPath() (Schema, string, error) {
	r0, r1, r2 := w.inner.GetSelectSchemaAndObjectPath()
	return Schema{inner: r0}, r1, r2
}

func (w StandardOperationStore) GetServers() (openapi3.Servers, bool) {
	r0, r1 := w.inner.GetServers()
	return r0, r1
}

func (w StandardOperationStore) IsAwaitable() bool {
	r0 := w.inner.IsAwaitable()
	return r0
}

func (w StandardOperationStore) IsNullary() bool {
	r0 := w.inner.IsNullary()
	return r0
}

func (w StandardOperationStore) ToPresentationMap(extended bool) map[string]interface{} {
	r0 := w.inner.ToPresentationMap(extended)
	return r0
}

type Tabulation struct {
	inner anysdk.Tabulation
}

func (w Tabulation) GetColumns() []anysdk.ColumnDescriptor {
	r0 := w.inner.GetColumns()
	return r0
}

func (w Tabulation) PushBackColumn(col anysdk.ColumnDescriptor) {
	w.inner.PushBackColumn(col)
	return
}

func (w Tabulation) RenameColumnsToXml() Tabulation {
	r0 := w.inner.RenameColumnsToXml()
	return Tabulation{inner: r0}
}

type TokenSemantic struct {
	inner anysdk.TokenSemantic
}

func (w TokenSemantic) GetKey() string {
	r0 := w.inner.GetKey()
	return r0
}

func (w TokenSemantic) GetLocation() string {
	r0 := w.inner.GetLocation()
	return r0
}

func (w TokenSemantic) GetTransformer() (anysdk.TokenTransformer, error) {
	r0, r1 := w.inner.GetTransformer()
	return r0, r1
}

type Transform struct {
	inner anysdk.Transform
}

func (w Transform) GetBody() string {
	r0 := w.inner.GetBody()
	return r0
}

func (w Transform) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

type View struct {
	inner anysdk.View
}

func (w View) GetDDL() string {
	r0 := w.inner.GetDDL()
	return r0
}

func (w View) GetNameNaive() string {
	r0 := w.inner.GetNameNaive()
	return r0
}

func (w View) GetRequiredParamNames() []string {
	r0 := w.inner.GetRequiredParamNames()
	return r0
}

type AuthUtility struct {
	inner auth_util.AuthUtility
}

func (w AuthUtility) ActivateAuth(authCtx *AuthCtx, principal string, authType string) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	w.inner.ActivateAuth(inner_authCtx, principal, authType)
	return
}

func (w AuthUtility) ApiTokenAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext, enforceBearer bool) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.ApiTokenAuth(inner_authCtx, httpContext, enforceBearer)
	return r0, r1
}

func (w AuthUtility) AuthRevoke(authCtx *AuthCtx) error {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0 := w.inner.AuthRevoke(inner_authCtx)
	return r0
}

func (w AuthUtility) AwsSigningAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.AwsSigningAuth(inner_authCtx, httpContext)
	return r0, r1
}

func (w AuthUtility) AzureDefaultAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.AzureDefaultAuth(inner_authCtx, httpContext)
	return r0, r1
}

func (w AuthUtility) BasicAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.BasicAuth(inner_authCtx, httpContext)
	return r0, r1
}

func (w AuthUtility) CustomAuth(authCtx *AuthCtx, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.CustomAuth(inner_authCtx, httpContext)
	return r0, r1
}

func (w AuthUtility) GCloudOAuth(runtimeCtx RuntimeCtx, authCtx *AuthCtx, enforceRevokeFirst bool) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.GCloudOAuth(runtimeCtx.inner, inner_authCtx, enforceRevokeFirst)
	return r0, r1
}

func (w AuthUtility) GenericOauthClientCredentials(authCtx *AuthCtx, scopes []string, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.GenericOauthClientCredentials(inner_authCtx, scopes, httpContext)
	return r0, r1
}

func (w AuthUtility) GetCurrentGCloudOauthUser() ([]byte, error) {
	r0, r1 := w.inner.GetCurrentGCloudOauthUser()
	return r0, r1
}

func (w AuthUtility) GoogleOauthServiceAccount(provider string, authCtx *AuthCtx, scopes []string, httpContext netutils.HTTPContext) (*http.Client, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.GoogleOauthServiceAccount(provider, inner_authCtx, scopes, httpContext)
	return r0, r1
}

func (w AuthUtility) ParseServiceAccountFile(ac *AuthCtx) (any, error) {
	var inner_ac *dto.AuthCtx
	if ac != nil {
		inner_ac = ac.inner
	}
	r0, r1 := w.inner.ParseServiceAccountFile(inner_ac)
	return r0, r1
}

type AnySdkClientConfigurator struct {
	inner client.AnySdkClientConfigurator
}

func (w AnySdkClientConfigurator) Auth(authCtx *AuthCtx, authTypeRequested string, enforceRevokeFirst bool) (client.AnySdkClient, error) {
	var inner_authCtx *dto.AuthCtx
	if authCtx != nil {
		inner_authCtx = authCtx.inner
	}
	r0, r1 := w.inner.Auth(inner_authCtx, authTypeRequested, enforceRevokeFirst)
	return r0, r1
}

type AnySdkResponse struct {
	inner client.AnySdkResponse
}

func (w AnySdkResponse) GetHttpResponse() (*http.Response, error) {
	r0, r1 := w.inner.GetHttpResponse()
	return r0, r1
}

type ControlAttributes struct {
	inner sqlcontrol.ControlAttributes
}

func (w ControlAttributes) GetControlGCStatusColumnName() string {
	r0 := w.inner.GetControlGCStatusColumnName()
	return r0
}

func (w ControlAttributes) GetControlGenIDColumnName() string {
	r0 := w.inner.GetControlGenIDColumnName()
	return r0
}

func (w ControlAttributes) GetControlInsIDColumnName() string {
	r0 := w.inner.GetControlInsIDColumnName()
	return r0
}

func (w ControlAttributes) GetControlInsertEncodedIDColumnName() string {
	r0 := w.inner.GetControlInsertEncodedIDColumnName()
	return r0
}

func (w ControlAttributes) GetControlLatestUpdateColumnName() string {
	r0 := w.inner.GetControlLatestUpdateColumnName()
	return r0
}

func (w ControlAttributes) GetControlMaxTxnColumnName() string {
	r0 := w.inner.GetControlMaxTxnColumnName()
	return r0
}

func (w ControlAttributes) GetControlSsnIDColumnName() string {
	r0 := w.inner.GetControlSsnIDColumnName()
	return r0
}

func (w ControlAttributes) GetControlTxnIDColumnName() string {
	r0 := w.inner.GetControlTxnIDColumnName()
	return r0
}

type AuthContexts struct {
	inner dto.AuthContexts
}

func (w AuthContexts) Clone() AuthContexts {
	r0 := w.inner.Clone()
	return AuthContexts{inner: r0}
}

type DataFlowCfg struct {
	inner dto.DataFlowCfg
}

func (w DataFlowCfg) GetMaxDependencies() int {
	r0 := w.inner.GetMaxDependencies()
	return r0
}

type NamespaceCfg struct {
	inner dto.NamespaceCfg
}

func (w NamespaceCfg) GetRegex() (*regexp.Regexp, error) {
	r0, r1 := w.inner.GetRegex()
	return r0, r1
}

func (w NamespaceCfg) GetTemplate() (*template.Template, error) {
	r0, r1 := w.inner.GetTemplate()
	return r0, r1
}

type OutputPacket struct {
	inner dto.OutputPacket
}

func (w OutputPacket) GetColumnNames() []string {
	r0 := w.inner.GetColumnNames()
	return r0
}

func (w OutputPacket) GetColumnOIDs() []oid.Oid {
	r0 := w.inner.GetColumnOIDs()
	return r0
}

func (w OutputPacket) GetRawRows() map[int]map[int]interface{} {
	r0 := w.inner.GetRawRows()
	return r0
}

func (w OutputPacket) GetRows() map[string]map[string]interface{} {
	r0 := w.inner.GetRows()
	return r0
}

type PgTLSCfg struct {
	inner dto.PgTLSCfg
}

func (w PgTLSCfg) GetKeyPair() (tls.Certificate, error) {
	r0, r1 := w.inner.GetKeyPair()
	return r0, r1
}

type SQLBackendCfg struct {
	inner dto.SQLBackendCfg
}

func (w SQLBackendCfg) GetDatabaseName() (string, error) {
	r0, r1 := w.inner.GetDatabaseName()
	return r0, r1
}

func (w SQLBackendCfg) GetIntelViewSchemaName() string {
	r0 := w.inner.GetIntelViewSchemaName()
	return r0
}

func (w SQLBackendCfg) GetOpsViewSchemaName() string {
	r0 := w.inner.GetOpsViewSchemaName()
	return r0
}

func (w SQLBackendCfg) GetSQLDialect() string {
	r0 := w.inner.GetSQLDialect()
	return r0
}

func (w SQLBackendCfg) GetSchemaType() string {
	r0 := w.inner.GetSchemaType()
	return r0
}

func (w SQLBackendCfg) GetTableSchemaName() string {
	r0 := w.inner.GetTableSchemaName()
	return r0
}

type SessionContext struct {
	inner dto.SessionContext
}

func (w SessionContext) GetIsolationLevel() constants.IsolationLevel {
	r0 := w.inner.GetIsolationLevel()
	return r0
}

func (w SessionContext) GetRollbackType() constants.RollbackType {
	r0 := w.inner.GetRollbackType()
	return r0
}

func (w SessionContext) UpdateIsolationLevel(p0 string) error {
	r0 := w.inner.UpdateIsolationLevel(p0)
	return r0
}

type TxnCoordinatorCfg struct {
	inner dto.TxnCoordinatorCfg
}

func (w TxnCoordinatorCfg) GetMaxTxnDepth() int {
	r0 := w.inner.GetMaxTxnDepth()
	return r0
}

type GQLReader struct {
	inner graphql.GQLReader
}

func (w GQLReader) Read() ([]map[string]interface{}, error) {
	r0, r1 := w.inner.Read()
	return r0, r1
}

type ExecPayload struct {
	inner internaldto.ExecPayload
}

func (w ExecPayload) GetPayloadMap() map[string]interface{} {
	r0 := w.inner.GetPayloadMap()
	return r0
}

type HTTPElement struct {
	inner internaldto.HTTPElement
}

func (w HTTPElement) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w HTTPElement) GetType() internaldto.HTTPElementType {
	r0 := w.inner.GetType()
	return r0
}

func (w HTTPElement) SetTransformer(transformer func(interface{}) (interface{}, error)) {
	w.inner.SetTransformer(transformer)
	return
}

func (w HTTPElement) IsTransformerPresent() bool {
	r0 := w.inner.IsTransformerPresent()
	return r0
}

func (w HTTPElement) Transformer(t interface{}) (interface{}, error) {
	r0, r1 := w.inner.Transformer(t)
	return r0, r1
}

type ExecutionResponse struct {
	inner local_template_executor.ExecutionResponse
}

func (w ExecutionResponse) GetStdErr() (*bytes.Buffer, bool) {
	r0, r1 := w.inner.GetStdErr()
	return r0, r1
}

func (w ExecutionResponse) GetStdOut() (*bytes.Buffer, bool) {
	r0, r1 := w.inner.GetStdOut()
	return r0, r1
}

type Executor struct {
	inner local_template_executor.Executor
}

func (w Executor) Execute(p0 map[string]any) (ExecutionResponse, error) {
	r0, r1 := w.inner.Execute(p0)
	return ExecutionResponse{inner: r0}, r1
}

type NameMangler struct {
	inner name_mangle.NameMangler
}

func (w NameMangler) MangleName(p0 string, p1 ...any) string {
	r0 := w.inner.MangleName(p0, p1)
	return r0
}

type ActionInsertPayload struct {
	inner providerinvoker.ActionInsertPayload
}

func (w ActionInsertPayload) GetItemisationResult() ItemisationResult {
	r0 := w.inner.GetItemisationResult()
	return ItemisationResult{inner: r0}
}

func (w ActionInsertPayload) GetParamsUsed() map[string]interface{} {
	r0 := w.inner.GetParamsUsed()
	return r0
}

func (w ActionInsertPayload) GetReqEncoding() string {
	r0 := w.inner.GetReqEncoding()
	return r0
}

func (w ActionInsertPayload) GetTableName() string {
	r0 := w.inner.GetTableName()
	return r0
}

func (w ActionInsertPayload) IsHousekeepingDone() bool {
	r0 := w.inner.IsHousekeepingDone()
	return r0
}

type ActionInsertResult struct {
	inner providerinvoker.ActionInsertResult
}

func (w ActionInsertResult) GetError() (error, bool) {
	r0, r1 := w.inner.GetError()
	return r0, r1
}

func (w ActionInsertResult) IsHousekeepingDone() bool {
	r0 := w.inner.IsHousekeepingDone()
	return r0
}

type InsertPreparator struct {
	inner providerinvoker.InsertPreparator
}

func (w InsertPreparator) ActionInsertPreparation(payload ActionInsertPayload) ActionInsertResult {
	r0 := w.inner.ActionInsertPreparation(payload.inner)
	return ActionInsertResult{inner: r0}
}

type Invoker struct {
	inner providerinvoker.Invoker
}

func (w Invoker) Invoke(ctx context.Context, req providerinvoker.Request) (providerinvoker.Result, error) {
	r0, r1 := w.inner.Invoke(ctx, req)
	return r0, r1
}

type ItemisationResult struct {
	inner providerinvoker.ItemisationResult
}

func (w ItemisationResult) GetItems() (interface{}, bool) {
	r0, r1 := w.inner.GetItems()
	return r0, r1
}

type Response struct {
	inner response.Response
}

func (w Response) Error() string {
	r0 := w.inner.Error()
	return r0
}

// type HTTPElement interface {
// 	GetName() string
// 	GetLocation() HTTPElementLocation
// }

type HTTPHTTPElement struct {
	inner httpelement.HTTPElement
}

func (w HTTPHTTPElement) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w HTTPHTTPElement) GetLocation() httpelement.HTTPElementLocation {
	r0 := w.inner.GetLocation()
	return r0
}

// TODO: fix this crap
func (w Response) ExtractElement(e HTTPHTTPElement) (interface{}, error) {
	r0, r1 := w.inner.ExtractElement(e.inner)
	return r0, r1
}

func (w Response) GetHttpResponse() *http.Response {
	r0 := w.inner.GetHttpResponse()
	return r0
}

func (w Response) GetProcessedBody() interface{} {
	r0 := w.inner.GetProcessedBody()
	return r0
}

func (w Response) HasError() bool {
	r0 := w.inner.HasError()
	return r0
}

type StreamTransformer struct {
	inner stream_transform.StreamTransformer
}

func (w StreamTransformer) GetOutStream() io.Reader {
	r0 := w.inner.GetOutStream()
	return r0
}

func (w StreamTransformer) Transform() error {
	r0 := w.inner.Transform()
	return r0
}

type StreamTransformerFactory struct {
	inner stream_transform.StreamTransformerFactory
}

func (w StreamTransformerFactory) GetTransformer(input string) (StreamTransformer, error) {
	r0, r1 := w.inner.GetTransformer(input)
	return StreamTransformer{inner: r0}, r1
}

func (w StreamTransformerFactory) IsTransformable() bool {
	r0 := w.inner.IsTransformable()
	return r0
}

type MapReader struct {
	inner streaming.MapReader
}

func (w MapReader) Read() ([]map[string]interface{}, error) {
	r0, r1 := w.inner.Read()
	return r0, r1
}

type MapStream struct {
	inner streaming.MapStream
}

func (w MapStream) Write(p0 []map[string]interface{}) error {
	r0 := w.inner.Write(p0)
	return r0
}

type MapStreamCollection struct {
	inner streaming.MapStreamCollection
}

func (w MapStreamCollection) Len() int {
	r0 := w.inner.Len()
	return r0
}

func (w MapStreamCollection) Push(p0 MapStream) {
	w.inner.Push(p0.inner)
	return
}

type AuthDTO struct {
	inner surface.AuthDTO
}

func (w AuthDTO) GetAccountID() string {
	r0 := w.inner.GetAccountID()
	return r0
}

func (w AuthDTO) GetAccountIDEnvVar() string {
	r0 := w.inner.GetAccountIDEnvVar()
	return r0
}

func (w AuthDTO) GetAuthStyle() int {
	r0 := w.inner.GetAuthStyle()
	return r0
}

func (w AuthDTO) GetClientID() string {
	r0 := w.inner.GetClientID()
	return r0
}

func (w AuthDTO) GetClientIDEnvVar() string {
	r0 := w.inner.GetClientIDEnvVar()
	return r0
}

func (w AuthDTO) GetClientSecret() string {
	r0 := w.inner.GetClientSecret()
	return r0
}

func (w AuthDTO) GetClientSecretEnvVar() string {
	r0 := w.inner.GetClientSecretEnvVar()
	return r0
}

func (w AuthDTO) GetEnvVarAPIKeyStr() string {
	r0 := w.inner.GetEnvVarAPIKeyStr()
	return r0
}

func (w AuthDTO) GetEnvVarAPISecretStr() string {
	r0 := w.inner.GetEnvVarAPISecretStr()
	return r0
}

func (w AuthDTO) GetEnvVarPassword() string {
	r0 := w.inner.GetEnvVarPassword()
	return r0
}

func (w AuthDTO) GetEnvVarUsername() string {
	r0 := w.inner.GetEnvVarUsername()
	return r0
}

func (w AuthDTO) GetGrantType() string {
	r0 := w.inner.GetGrantType()
	return r0
}

func (w AuthDTO) GetInlineBasicCredentials() string {
	r0 := w.inner.GetInlineBasicCredentials()
	return r0
}

func (w AuthDTO) GetKeyEnvVar() string {
	r0 := w.inner.GetKeyEnvVar()
	return r0
}

func (w AuthDTO) GetKeyFilePath() string {
	r0 := w.inner.GetKeyFilePath()
	return r0
}

func (w AuthDTO) GetKeyFilePathEnvVar() string {
	r0 := w.inner.GetKeyFilePathEnvVar()
	return r0
}

func (w AuthDTO) GetKeyID() string {
	r0 := w.inner.GetKeyID()
	return r0
}

func (w AuthDTO) GetKeyIDEnvVar() string {
	r0 := w.inner.GetKeyIDEnvVar()
	return r0
}

func (w AuthDTO) GetLocation() string {
	r0 := w.inner.GetLocation()
	return r0
}

func (w AuthDTO) GetName() string {
	r0 := w.inner.GetName()
	return r0
}

func (w AuthDTO) GetScopes() []string {
	r0 := w.inner.GetScopes()
	return r0
}

func (w AuthDTO) GetSubject() string {
	r0 := w.inner.GetSubject()
	return r0
}

func (w AuthDTO) GetSuccessor() (AuthDTO, bool) {
	r0, r1 := w.inner.GetSuccessor()
	return AuthDTO{inner: r0}, r1
}

func (w AuthDTO) GetTokenURL() string {
	r0 := w.inner.GetTokenURL()
	return r0
}

func (w AuthDTO) GetType() string {
	r0 := w.inner.GetType()
	return r0
}

func (w AuthDTO) GetValuePrefix() string {
	r0 := w.inner.GetValuePrefix()
	return r0
}

func (w AuthDTO) GetValues() url.Values {
	r0 := w.inner.GetValues()
	return r0
}

type IDiscoveryAdapter struct {
	inner discovery.IDiscoveryAdapter
}

func (w IDiscoveryAdapter) GetProvider(providerKey string) (Provider, error) {
	r0, r1 := w.inner.GetProvider(providerKey)
	return Provider{inner: r0}, r1
}

func (w IDiscoveryAdapter) GetResourcesMap(prov Provider, serviceKey string) (map[string]Resource, error) {
	r0, r1 := w.inner.GetResourcesMap(prov.inner, serviceKey)
	return wrapMapString_Resource(r0), r1
}

func (w IDiscoveryAdapter) GetServiceHandlesMap(prov Provider) (map[string]ProviderService, error) {
	r0, r1 := w.inner.GetServiceHandlesMap(prov.inner)
	return wrapMapString_ProviderService(r0), r1
}

func (w IDiscoveryAdapter) GetServiceShard(prov Provider, serviceKey string, resourceKey string) (Service, error) {
	r0, r1 := w.inner.GetServiceShard(prov.inner, serviceKey, resourceKey)
	return Service{inner: r0}, r1
}

func (w IDiscoveryAdapter) PersistStaticExternalSQLDataSource(prov Provider) error {
	r0 := w.inner.PersistStaticExternalSQLDataSource(prov.inner)
	return r0
}

type AddressSpaceFormulator struct {
	inner radix_tree_address_space.AddressSpaceFormulator
}

func (w AddressSpaceFormulator) Formulate() error {
	r0 := w.inner.Formulate()
	return r0
}

func (w AddressSpaceFormulator) GetAddressSpace() AddressSpace {
	r0 := w.inner.GetAddressSpace()
	return AddressSpace{inner: r0}
}

type SQLEngine struct {
	inner sqlengine.SQLEngine
}

func (w SQLEngine) CacheStoreGet(p0 string) ([]byte, error) {
	r0, r1 := w.inner.CacheStoreGet(p0)
	return r0, r1
}

func (w SQLEngine) CacheStorePut(p0 string, p1 []byte, p2 string, p3 int) error {
	r0 := w.inner.CacheStorePut(p0, p1, p2, p3)
	return r0
}

func (w SQLEngine) Exec(p0 string, p1 ...interface{}) (sql.Result, error) {
	r0, r1 := w.inner.Exec(p0, p1)
	return r0, r1
}

func (w SQLEngine) ExecInTxn(queries []string) error {
	r0 := w.inner.ExecInTxn(queries)
	return r0
}

func (w SQLEngine) GetCurrentDiscoveryGenerationID(discoveryID string) (int, error) {
	r0, r1 := w.inner.GetCurrentDiscoveryGenerationID(discoveryID)
	return r0, r1
}

func (w SQLEngine) GetCurrentGenerationID() (int, error) {
	r0, r1 := w.inner.GetCurrentGenerationID()
	return r0, r1
}

func (w SQLEngine) GetDB() (*sql.DB, error) {
	r0, r1 := w.inner.GetDB()
	return r0, r1
}

func (w SQLEngine) GetNextDiscoveryGenerationID(discoveryID string) (int, error) {
	r0, r1 := w.inner.GetNextDiscoveryGenerationID(discoveryID)
	return r0, r1
}

func (w SQLEngine) GetNextGenerationID() (int, error) {
	r0, r1 := w.inner.GetNextGenerationID()
	return r0, r1
}

func (w SQLEngine) GetNextSessionID(p0 int) (int, error) {
	r0, r1 := w.inner.GetNextSessionID(p0)
	return r0, r1
}

func (w SQLEngine) GetTx() (*sql.Tx, error) {
	r0, r1 := w.inner.GetTx()
	return r0, r1
}

func (w SQLEngine) Query(p0 string, p1 ...interface{}) (*sql.Rows, error) {
	r0, r1 := w.inner.Query(p0, p1)
	return r0, r1
}

func (w SQLEngine) QueryRow(query string, args ...any) *sql.Row {
	r0 := w.inner.QueryRow(query, args)
	return r0
}
